from collections.abc import Sequence
from typing import Any, final

import numpy as np

@final
class Nuclide:
    """A nuclide identifier with naming-convention conversions."""

    def __init__(self, name: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def nucid(self) -> int: ...
    @property
    def zzaaam(self) -> int: ...
    @property
    def z(self) -> int: ...
    @property
    def a(self) -> int: ...
    @property
    def state(self) -> int: ...
    @property
    def zaid(self) -> int: ...
    @property
    def zzllaaam(self) -> str: ...
    @property
    def serpent(self) -> str: ...
    @property
    def nist(self) -> str: ...
    @property
    def cinder(self) -> int: ...
    @property
    def alara(self) -> str: ...
    @property
    def sza(self) -> int: ...
    @property
    def mass(self) -> float | None: ...
    @property
    def abundance(self) -> float | None: ...
    def fluka(self) -> str: ...

@final
class Particle:
    """A particle species with cross-code name translations."""

    def __init__(self, spec: str | int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def describe(self) -> str: ...
    def mcnp(self) -> str | None: ...
    def mcnp6(self) -> str | None: ...
    def fluka(self) -> str | None: ...
    def geant4(self) -> str | None: ...

@final
class XsdirTable:
    """One xsdir directory entry."""
    @property
    def name(self) -> str: ...
    @property
    def awr(self) -> float: ...
    @property
    def filename(self) -> str: ...
    @property
    def filetype(self) -> int: ...
    @property
    def address(self) -> int: ...
    @property
    def tablelength(self) -> int: ...
    @property
    def temperature(self) -> float | None: ...
    @property
    def ptable(self) -> bool: ...
    def zaid(self) -> str: ...
    def to_serpent(self, directory: str = "") -> str: ...

@final
class Xsdir:
    """Parsed MCNP xsdir cross-section index."""
    @property
    def datapath(self) -> str | None: ...
    @property
    def awr(self) -> dict[int, float]: ...
    @property
    def tables(self) -> list[XsdirTable]: ...
    def find_table(self, name: str) -> list[XsdirTable]: ...
    def nucs(self) -> list[int]: ...

@final
class MeshTally:
    """One fmesh4 tally from a meshtal file."""
    @property
    def tally_number(self) -> int: ...
    @property
    def particle(self) -> str: ...
    @property
    def dose_response(self) -> bool: ...
    @property
    def x_bounds(self) -> list[float]: ...
    @property
    def y_bounds(self) -> list[float]: ...
    @property
    def z_bounds(self) -> list[float]: ...
    @property
    def e_bounds(self) -> list[float]: ...
    @property
    def result(self) -> list[list[float]]: ...
    @property
    def rel_error(self) -> list[list[float]]: ...
    @property
    def total_result(self) -> list[float]: ...
    @property
    def total_rel_error(self) -> list[float]: ...
    def dims(self) -> tuple[int, int, int]: ...
    def num_ves(self) -> int: ...
    def num_e_groups(self) -> int: ...
    def cell(self, i: int, j: int, k: int) -> tuple[list[float], list[float]]: ...
    def cell_total(self, i: int, j: int, k: int) -> tuple[float, float]: ...
    def to_list(self) -> tuple[list[list[float]], list[list[float]]]: ...
    def totals_list(self) -> tuple[list[float], list[float]]: ...
    def result_array(self) -> tuple[np.ndarray, np.ndarray]: ...
    def totals_array(self) -> tuple[np.ndarray, np.ndarray]: ...

@final
class Meshtal:
    """Parsed MCNP meshtal file."""
    @property
    def version(self) -> str: ...
    @property
    def ld(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def histories(self) -> int: ...
    @property
    def tallies(self) -> dict[int, MeshTally]: ...

@final
class Wwinp:
    """Parsed MCNP WWINP weight-window file (Cartesian)."""
    @property
    def ni(self) -> int: ...
    @property
    def nr(self) -> int: ...
    @property
    def ne(self) -> list[int]: ...
    @property
    def nf(self) -> tuple[int, int, int]: ...
    @property
    def origin(self) -> tuple[float, float, float]: ...
    @property
    def nc(self) -> tuple[int, int, int]: ...
    @property
    def cm(self) -> list[list[float]]: ...
    @property
    def bounds(self) -> list[list[float]]: ...
    @property
    def e(self) -> list[list[float]]: ...
    def ww_row(self, particle: int, group: int) -> list[float]: ...
    def ww_column(self, particle: int, ve: int) -> list[float]: ...
    def ww_row_array(self, particle: int, group: int) -> np.ndarray: ...
    def ww_column_array(self, particle: int, ve: int) -> np.ndarray: ...
    def ww_particle_array(self, particle: int) -> np.ndarray: ...

@final
class Mctal:
    """Parsed MCNP MCTAL file: header, standard + mesh tally bodies, and kcode data."""
    @property
    def code_name(self) -> str: ...
    @property
    def comment(self) -> str: ...
    @property
    def n_histories(self) -> int: ...
    @property
    def n_cycles(self) -> int: ...
    @property
    def n_inactive(self) -> int: ...
    @property
    def vars_per_cycle(self) -> int: ...
    @property
    def npert(self) -> str | None: ...
    @property
    def tally_nums(self) -> list[int]: ...
    @property
    def tallies(self) -> list[dict[str, Any]]: ...
    @property
    def mesh_tallies(self) -> list[dict[str, Any]]: ...
    @property
    def k_col(self) -> list[float]: ...
    @property
    def k_abs(self) -> list[float]: ...
    @property
    def k_path(self) -> list[float]: ...
    @property
    def prompt_life_col(self) -> list[float]: ...
    @property
    def prompt_life_path(self) -> list[float]: ...
    @property
    def averages(self) -> list[dict[str, float]]: ...
    def k_arrays(
        self,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]: ...
    def averages_array(self) -> np.ndarray: ...
    def tally_vals_array(self, number: int) -> np.ndarray: ...
    def mesh_tally_vals_array(self, number: int) -> np.ndarray: ...

@final
class McplFile:
    """Parsed MCPL particle-list file (header eagerly; particles on demand)."""
    @property
    def version(self) -> int: ...
    @property
    def nparticles(self) -> int: ...
    @property
    def srcname(self) -> str: ...
    @property
    def comments(self) -> list[str]: ...
    @property
    def has_userflags(self) -> bool: ...
    @property
    def has_polarisation(self) -> bool: ...
    @property
    def double_prec(self) -> bool: ...
    @property
    def universal_pdgcode(self) -> int | None: ...
    @property
    def universal_weight(self) -> float | None: ...
    @property
    def blobs(self) -> list[tuple[str, bytes]]: ...
    def particles(self) -> list[dict[str, Any]]: ...

@final
class SurfSrc:
    """Parsed MCNP SSW surface-source file."""
    @property
    def kod(self) -> str: ...
    @property
    def ver(self) -> str: ...
    @property
    def np1(self) -> int: ...
    @property
    def orignp1(self) -> int: ...
    @property
    def nrss(self) -> int: ...
    @property
    def ncrd(self) -> int: ...
    @property
    def njsw(self) -> int: ...
    @property
    def niss(self) -> int: ...
    def print_header(self) -> str: ...
    def tracks(self) -> list[dict[str, float]]: ...

@final
class Chain:
    """Parsed depletion chain (XML format)."""
    @property
    def nuclides(self) -> list[str]: ...
    def index_of(self, name: str) -> int | None: ...

@final
class DepletionSystem:
    """Pre-built depletion system for repeated CRAM/Bateman solves."""
    def solve(
        self, n0: dict[str, float], dt: float, order: int = 48, method: str = "cram48"
    ) -> dict[str, float]: ...
    def solve_vec(
        self, n0: list[float], dt: float, order: int = 48, method: str = "cram48"
    ) -> list[float]: ...

@final
class Cascade:
    """Enrichment cascade with numeric multicomponent solving."""
    @staticmethod
    def default_uranium() -> Cascade: ...
    def __init__(
        self,
        alpha: float,
        Mstar: float,
        j: int,
        k: int,
        N: float,
        M: float,
        x_feed_j: float,
        x_prod_j: float,
        x_tail_j: float,
        mat_feed: dict[str, float],
    ) -> None: ...
    def solve(self, tolerance: float | None = None, max_iterations: int | None = None) -> None: ...
    def solve_multicomponent(
        self, tolerance: float | None = None, max_iterations: int | None = None
    ) -> None: ...
    @property
    def alpha(self) -> float: ...
    @property
    def Mstar(self) -> float: ...
    @property
    def N(self) -> float: ...
    @property
    def M(self) -> float: ...
    @property
    def x_feed_j(self) -> float: ...
    @property
    def x_prod_j(self) -> float: ...
    @property
    def x_tail_j(self) -> float: ...
    @property
    def l_t_per_feed(self) -> float: ...
    @property
    def swu_per_feed(self) -> float: ...
    @property
    def swu_per_prod(self) -> float: ...
    @property
    def mat_feed(self) -> dict[str, float]: ...
    @property
    def mat_prod(self) -> dict[str, float]: ...
    @property
    def mat_tail(self) -> dict[str, float]: ...
    def separative_work_per_product(self) -> float: ...

@final
class MaterialsCompendium:
    """PNNL/DOE Materials Compendium (411 named materials)."""
    @staticmethod
    def load(path: str) -> MaterialsCompendium: ...
    def __len__(self) -> int: ...
    def names(self) -> list[str]: ...
    def get(self, name: str, as_material: bool = False) -> dict[str, Any] | None: ...

@final
class UsrbinTally:
    """One FLUKA USRBIN detector."""
    @property
    def name(self) -> str: ...
    @property
    def particle(self) -> str: ...
    @property
    def nx(self) -> int: ...
    @property
    def ny(self) -> int: ...
    @property
    def nz(self) -> int: ...
    @property
    def x_bounds(self) -> list[float]: ...
    @property
    def y_bounds(self) -> list[float]: ...
    @property
    def z_bounds(self) -> list[float]: ...
    @property
    def data(self) -> list[float]: ...
    @property
    def error(self) -> list[float]: ...
    def dims(self) -> tuple[int, int, int]: ...

@final
class MagicOutput:
    """MAGIC weight-window generation output."""
    @property
    def lower_bounds_ww(self) -> list[float]: ...
    @property
    def groups_per_ve(self) -> int: ...
    @property
    def scale_factors(self) -> list[float]: ...
    @property
    def e_upper_bounds(self) -> list[float]: ...
    @property
    def ww_tag_name(self) -> str: ...

@final
class AliasTable:
    """Walker alias table for discrete sampling."""
    def __init__(self, pdf: list[float]) -> None: ...
    def sample(self, r1: float, r2: float) -> int: ...
    @property
    def pdf(self) -> list[float]: ...
    def __len__(self) -> int: ...

@final
class MeshSourceSampler:
    """Mesh source sampler over a meshtal tally (analog/uniform/user)."""
    def __init__(
        self, tally: MeshTally, mode: str, user_pdf: list[float] | None = None
    ) -> None: ...
    def sample(self, r1: float, r2: float) -> dict[str, float]: ...
    def mode(self) -> str: ...
    def num_voxels(self) -> int: ...
    def table_len(self) -> int: ...

@final
class PtracFile:
    """Parsed MCNP PTRAC event file."""
    @property
    def problem_title(self) -> str: ...
    @property
    def width_code(self) -> int: ...
    @property
    def variable_nums(self) -> dict[str, int]: ...
    def events(self) -> list[dict[str, float]]: ...
    def events_array(self) -> np.ndarray: ...
    def event_field_array(self, field: str) -> np.ndarray: ...

@final
class EndlLibrary:
    """Parsed ENDL evaluation file (EEDL/EPDL scope)."""
    def nuclides(self) -> list[int]: ...
    def get_rx(
        self,
        nuc: int | str,
        p_in: int,
        rdesc: int,
        rprop: int,
        x1: int | None = None,
        p_out: int | None = None,
    ) -> list[list[float]]: ...

def read_endl(path: str) -> EndlLibrary: ...
def endl_endftod(field: str) -> float: ...
def combine_ssw_files(output: str, inputs: list[str]) -> None: ...
def from_zaid(zaid: int) -> Nuclide: ...
def atomic_mass(key: int | str) -> float | None: ...
def natural_abundance(key: int | str) -> float | None: ...
def rxname_id(name: str) -> int: ...
def rxname_name(id: int) -> str | None: ...
def rxname_mt(id: int) -> int: ...
def rxname_label(id: int) -> str: ...
def rxname_doc(id: int) -> str: ...
def rxname_reaction(id: int) -> dict[str, Any] | None: ...
def rxname_id_from_nucdelta(from_nucid: int, to_nucid: int, projectile: str = "n") -> int: ...
def rxname_child(parent: str, rx: int | str, projectile: str = "n") -> str: ...
def rxname_parent(child: str, rx: int | str, projectile: str = "n") -> str: ...
def particle_is_valid(spec: str) -> bool: ...
def particle_is_valid_pdc(n: int) -> bool: ...
def particle_is_hydrogen(spec: str) -> bool: ...
def particle_is_heavy_ion(spec: str) -> bool: ...
def dose_f1(name: str, source: str = "EPA") -> float | None: ...
def dose_lung_model(name: str, source: str = "EPA") -> str | None: ...
def read_xsdir(path: str) -> Xsdir: ...
def read_meshtal(path: str) -> Meshtal: ...
def read_wwinp(path: str) -> Wwinp: ...
def read_mctal(path: str) -> Mctal: ...
def read_ssw(path: str) -> SurfSrc: ...
def read_ptrac(path: str) -> PtracFile: ...
def read_mcpl(path: str) -> McplFile: ...
def write_mcpl(path: str, header: dict[str, Any], particles: list[dict[str, Any]]) -> None: ...
def ssw2mcpl(
    ssw_path: str,
    mcpl_path: str,
    surfs: list[int],
    kinds: list[str],
    options: dict[str, Any] | None = None,
) -> int: ...
def mcpl2ssw(
    mcpl_path: str,
    reference_ssw_path: str,
    ssw_out_path: str,
    surface: int | None = None,
    force_cs_to_one: bool = False,
    niss: int | None = None,
    allow_polarisation: bool = False,
) -> int: ...
def half_life(key: int | str) -> float | None: ...
def decay_constant(key: int | str) -> float | None: ...
def q_value_capture(key: int | str) -> float | None: ...
def q_value_alpha(key: int | str) -> float | None: ...
def simple_xs(name: str) -> tuple[float, float] | None: ...
def scattering_length(name: str) -> float | None: ...
def decay_energy(name: str) -> float | None: ...
def decay_branches(name: str) -> list[tuple[str, float, str]]: ...
def decay_branch_fraction(parent: str, progeny: str) -> float | None: ...
def normalize_nuclide(name: str) -> str: ...
def decay_heat(comp: dict[str, float]) -> float: ...
def dose_factor(name: str, pathway: str, source: str = "EPA") -> float | None: ...
def dose_per_g(comp: dict[str, float], pathway: str, source: str = "EPA") -> float: ...
def mix_by_mass(parts: list[tuple[dict[str, float], float]]) -> dict[str, float]: ...
def mix_by_volume(parts: list[tuple[dict[str, float], float, float]]) -> dict[str, float]: ...
def specific_activity(comp: dict[str, float]) -> float: ...
def materials_doc_to_xml(
    entries: list[tuple[str, dict[str, float], float]], cross_sections: str | None = None
) -> str: ...
def expand_elements(comp: dict[str, float]) -> dict[str, float]: ...
def collapse_elements(comp: dict[str, float]) -> dict[str, float]: ...
def read_inp(path: str) -> list[dict[str, Any]]: ...
def from_formula(formula: str) -> dict[str, float]: ...
def activity(comp: dict[str, float]) -> dict[str, float]: ...
def to_xml(comp: dict[str, float], name: str, density: float, units: str = "g/cm3") -> str: ...
def read_serpent(path: str, kind: str) -> dict[str, Any]: ...
def read_usrbin(path: str) -> list[UsrbinTally]: ...
def fluka_material_str(fid: int, nuc: str, density: float) -> str: ...
def fluka_compound_str(
    fid: int,
    compound_name: str,
    density: float,
    frac_type: str = "mass",
    components: list[tuple[str, float]] | None = None,
) -> str: ...
def fluka_builtin_set() -> list[str]: ...
def magic(tally: MeshTally, per_group: bool = False, tolerance: float = 0.5) -> MagicOutput: ...
def magic_with(
    tally: MeshTally, selection: str = "total", tolerance: float = 0.5, null_value: float = 0.0
) -> MagicOutput: ...
def write_ssw(ssw: SurfSrc, path: str, tracks: list[dict[str, float]] | None = None) -> None: ...
def mesh_to_geom(
    x_bounds: Sequence[float],
    y_bounds: Sequence[float],
    z_bounds: Sequence[float],
    cell_materials: Sequence[tuple[str, float] | None],
    title_card: str,
) -> str: ...
def alara_parse_deck(text: str) -> dict[str, Any]: ...
def alara_parse_flux(text: str, name: str) -> dict[str, Any]: ...
def alara_parse_output(text: str, run_lbl: str) -> list[dict[str, Any]]: ...
def alara_expand_schedule(deck_text: str, top: str | None = None) -> list[dict[str, Any]]: ...
def alara_validate_deck(text: str) -> None: ...
def alara_check_block(block: str, line: int) -> None: ...
def alara_flux_total(name: str, text: str) -> float: ...
def alara_flux_len(name: str, text: str) -> int: ...
def alara_output_totals(text: str, run_lbl: str) -> list[dict[str, Any]]: ...
def alara_output_total_activity(text: str, run_lbl: str) -> float: ...
def alara_photon_total_strength(text: str) -> float: ...
def alara_schedule_total_time(deck_text: str, top: str | None = None) -> float: ...
def read_chain(path: str) -> Chain: ...
def build_depletion_system(chain: Chain, rates: dict[str, float]) -> DepletionSystem: ...
def deplete(
    chain: Chain,
    n0: dict[str, float],
    dt: float,
    rates: dict[str, float] | None = None,
    order: int = 48,
    method: str = "cram48",
) -> dict[str, float]: ...
def deplete_series(
    chain: Chain,
    n0: dict[str, float],
    dts: list[float],
    rates: dict[str, float] | None = None,
    rates_list: list[dict[str, float] | None] | None = None,
    integrator: str = "predictor",
    order: int = 48,
    method: str = "cram48",
) -> dict[str, Any]: ...
def isotxs_parse(text: str) -> dict[str, Any]: ...
def rtflux_parse(text: str, kind: str = "rtflux") -> dict[str, Any]: ...
def cccc_rtflux_npoints(text: str, kind: str = "rtflux") -> int: ...
def cccc_rtflux_point(text: str, kind: str = "rtflux", index: int = 0) -> list[float] | None: ...
def cccc_rtflux_total(text: str, kind: str = "rtflux") -> float: ...
def cccc_isotxs_find(text: str, label: str) -> dict[str, Any] | None: ...
def cccc_isotxs_len(text: str) -> int: ...
def partisn_render(deck: dict[str, Any]) -> str: ...
def partisn_validate(deck: dict[str, Any], isotxs_text: str) -> None: ...
def fispact_parse_output(text: str, run_lbl: str) -> list[dict[str, Any]]: ...
def fispact_is_output(path: str) -> bool: ...
def origen_parse_tape5(text: str) -> dict[str, Any]: ...
def origen_parse_tape6(text: str) -> dict[str, Any]: ...
def origen_parse_tape9(text: str) -> list[dict[str, Any]]: ...
def origen_tape6_find(text: str, nuclide: str) -> dict[str, Any] | None: ...
def origen_tape6_total_activity(text: str) -> float: ...
def origen_tape9_find(text: str, nuclide: str) -> dict[str, Any] | None: ...
def r2s_from_deck(deck_text: str) -> dict[str, Any]: ...
def r2s_from_snapshot(snapshot: dict[str, Any]) -> dict[str, Any]: ...
def r2s_validate(workflow: dict[str, Any], deck_text: str) -> None: ...
def r2s_expand(deck_text: str, top: str | None = None) -> list[dict[str, Any]]: ...
def r2s_assemble(output_text: str, run_lbl: str, zone: str, groups: int) -> dict[str, Any]: ...
def r2s_tag_zone_strength(
    totals: list[float], zone_of_voxel: list[int], split: bool = False
) -> dict[str, Any]: ...
def r2s_photon_group_sums(
    photon_text: str, nuclides: list[str], time_s: float
) -> dict[str, Any]: ...

@final
class DeckProblem:
    """Parsed MCNP input deck with format-preserving write-back."""
    @staticmethod
    def loads(text: str) -> DeckProblem: ...
    @property
    def message(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def cells(self) -> list[dict[str, str]]: ...
    @property
    def surfs(self) -> list[dict[str, str]]: ...
    @property
    def material_numbers(self) -> list[int]: ...
    @property
    def data_names(self) -> list[str]: ...
    @property
    def mode(self) -> dict[str, str]: ...
    @property
    def transforms(self) -> list[dict[str, str]]: ...
    @property
    def universes(self) -> list[dict[str, str]]: ...
    @property
    def lattices(self) -> list[dict[str, str]]: ...
    @property
    def fills(self) -> list[dict[str, str]]: ...
    @property
    def importances(self) -> list[dict[str, str]]: ...
    @property
    def volumes(self) -> list[dict[str, str]]: ...
    @property
    def tallies(self) -> list[dict[str, str]]: ...
    def dumps(self) -> str: ...
    def validate(self) -> None: ...
    def validation_notes(self) -> list[str]: ...
    def set_cell_density(self, cell: int, dens: float) -> None: ...
    def set_cell_material(self, cell: int, mat: int) -> None: ...
    def set_mode(self, particles: list[str]) -> None: ...
    def set_cell_universe(self, cell: int, universe: int, not_truncated: bool) -> None: ...
    def set_cell_lattice(self, cell: int, lattice: int | None) -> None: ...
    def set_cell_fill(self, cell: int, universe: int) -> None: ...

@final
class Inventory:
    """Unit-aware decay inventory over a depletion chain."""
    def __init__(self, chain: Chain, comp: dict[str, float], units: str = "atoms") -> None: ...
    def numbers(self) -> dict[str, float]: ...
    def decay(
        self,
        dt: float,
        time_unit: str = "s",
        rates: dict[str, float] | None = None,
        order: int = 48,
        method: str = "cram48",
    ) -> Inventory: ...
    def activities(self, units: str) -> dict[str, float]: ...
    def masses(self, units: str) -> dict[str, float]: ...
    def moles(self, units: str) -> dict[str, float]: ...
    def activity_fractions(self) -> dict[str, float]: ...
    def mass_fractions(self) -> dict[str, float]: ...
    def mole_fractions(self) -> dict[str, float]: ...
    def half_lives_readable(self) -> dict[str, str]: ...
    def add(self, other: Inventory) -> Inventory: ...
    def sub(self, other: Inventory) -> Inventory: ...
    def mul(self, scalar: float) -> Inventory: ...
    def div(self, scalar: float) -> Inventory: ...
    def to_csv(self) -> str: ...
    @staticmethod
    def from_csv(chain: Chain, text: str) -> Inventory: ...

def parse_deck(text: str) -> DeckProblem: ...
def read_deck(path: str) -> DeckProblem: ...
def cumulative_decays(
    chain: Chain,
    n0: dict[str, float],
    dt: float,
    rates: dict[str, float] | None = None,
) -> dict[str, float]: ...
def kinetics_solve(
    betas: list[float],
    lambdas: list[float],
    lambda_gen: float,
    rho: dict[str, Any],
    t: list[float],
    n0: float,
    c0: list[float] | None = None,
    method: str = "trapezoidal",
    rtol: float = 1e-9,
    atol: float = 1e-12,
    dt_min: float = 1e-14,
    dt_max: float | None = None,
    max_steps: int = 1000000,
) -> dict[str, Any]: ...
def kinetics_equilibrium(
    betas: list[float], lambdas: list[float], lambda_gen: float, n0: float
) -> list[float]: ...
def kinetics_initial_rate(
    betas: list[float],
    lambdas: list[float],
    lambda_gen: float,
    rho: dict[str, Any],
    n0: float,
    c0: list[float] | None = None,
) -> float: ...
def kinetics_inhour_rho(
    betas: list[float], lambdas: list[float], lambda_gen: float, omega: float
) -> float: ...
def kinetics_stable_period(
    betas: list[float], lambdas: list[float], lambda_gen: float, rho: float
) -> float: ...
def kinetics_prompt_jump(
    n_before: float, rho_before: float, rho_after: float, beta_total: float
) -> float: ...
def kinetics_from_ifp(
    betas: list[float], lambda_gen: float, lambdas: list[float]
) -> dict[str, Any]: ...
def spectroscopy_rect_smooth(counts: list[float], m: int) -> list[float]: ...
def spectroscopy_five_point_smooth(counts: list[float]) -> list[float]: ...
def spectroscopy_calc_bg(
    counts: list[float], channels: list[float], c1: int, c2: int, m: int
) -> float: ...
def spectroscopy_gross_count(
    counts: list[float], channels: list[float], c1: int, c2: int
) -> float: ...
def spectroscopy_net_counts(
    counts: list[float], channels: list[float], c1: int, c2: int, m: int
) -> float: ...
def spectroscopy_energy_bins(channels: list[float], calib_e_fit: list[float]) -> list[float]: ...
def spectroscopy_detector_efficiency(
    energy_mev: float, eff_coeff: list[float], eff_fit: int
) -> float: ...
def spectroscopy_fit_efficiency(
    energies: list[float],
    effs: list[float],
    weights: list[float],
    order: int,
    eff_fit: int = 1,
) -> list[float]: ...
def spectroscopy_xray_lines(
    atomic: dict[str, float],
    k_conv: float | None = None,
    l_conv: float | None = None,
) -> list[tuple[float, float]]: ...
def spectroscopy_sdef_decay_source(
    lines: list[tuple[float, float]],
    x: float = 0.0,
    y: float = 0.0,
    z: float = 0.0,
    u: float = 0.0,
    v: float = 0.0,
    w: float = 0.0,
    weight: float = 1.0,
    particle: str = "Neutron",
    version: int = 5,
) -> tuple[list[tuple[float, float]], str]: ...
def spectroscopy_parse_dollar_spe(text: str) -> dict[str, Any]: ...
def spectroscopy_parse_spe(text: str) -> dict[str, Any]: ...
def spectroscopy_read_dollar_spe(path: str) -> dict[str, Any]: ...
def spectroscopy_read_spe(path: str) -> dict[str, Any]: ...
def spectroscopy_parse_lines_tsv(text: str) -> list[tuple[float, float]]: ...
def spectroscopy_read_decay_lines(path: str) -> list[tuple[float, float]]: ...
def uq_sample_mvn(
    mean: list[float], cov: list[list[float]], n: int, seed: int
) -> dict[str, Any]: ...
def uq_sample_lognormal(
    mean_log: list[float], cov: list[list[float]], n: int, seed: int
) -> dict[str, Any]: ...
def uq_lognormal_mean(mean_log: list[float], cov: list[list[float]]) -> list[float]: ...
def uq_lognormal_cov(mean_log: list[float], cov: list[list[float]]) -> list[list[float]]: ...
def uq_sample_mean(samples: list[list[float]]) -> list[float]: ...
def uq_sample_cov(samples: list[list[float]]) -> list[list[float]]: ...
def uq_check_convergence(
    mean: list[float],
    cov: list[list[float]],
    samples: list[list[float]],
    mean_tol: float,
    cov_tol: float,
) -> dict[str, Any]: ...
def uq_perturb_branches(base: list[float], rel: list[float]) -> list[float]: ...
def uq_perturb_energies(base: list[float], delta: list[float], convention: str) -> list[float]: ...
def uq_passthrough(delta: list[float]) -> list[float]: ...
def uq_perturb_fission_yields(base: list[float], rel: list[float]) -> list[float]: ...
def progeny(chain: Chain, name: str) -> list[tuple[str, float, str]]: ...
def branching_fraction(chain: Chain, parent: str, child: str) -> float | None: ...
def decay_mode(chain: Chain, parent: str, child: str) -> str | None: ...
def chain_edges(chain: Chain) -> list[tuple[str, str, float, str]]: ...
def armi_to_nucid(name: str) -> Nuclide: ...
def nucid_to_armi(nuclide: Nuclide) -> str: ...
def mcc3_to_nucid(name: str) -> Nuclide: ...
def check_labels(
    comp: dict[str, float], widths: list[int] | None = None
) -> list[dict[str, Any]]: ...
def audit_material(comp: dict[str, float]) -> list[dict[str, str]]: ...
def separate_material(
    comp: dict[str, float], effs: dict[str, float]
) -> tuple[dict[str, float], dict[str, float]]: ...
def blend_material(parts: list[tuple[dict[str, float], float]]) -> dict[str, float]: ...
def enrichment_value_func(x: float) -> float: ...
def enrichment_swu_per_feed(x_feed: float, x_prod: float, x_tail: float) -> float: ...
def enrichment_swu_per_prod(x_feed: float, x_prod: float, x_tail: float) -> float: ...
def enrichment_swu_per_tail(x_feed: float, x_prod: float, x_tail: float) -> float: ...
def enrichment_prod_per_feed(x_feed: float, x_prod: float, x_tail: float) -> float: ...
def enrichment_tail_per_feed(x_feed: float, x_prod: float, x_tail: float) -> float: ...
def enrichment_tail_per_prod(x_feed: float, x_prod: float, x_tail: float) -> float: ...
def enrichment_feed_per_prod(x_feed: float, x_prod: float, x_tail: float) -> float: ...
def enrichment_feed_per_tail(x_feed: float, x_prod: float, x_tail: float) -> float: ...
def enrichment_prod_per_tail(x_feed: float, x_prod: float, x_tail: float) -> float: ...
def enrichment_alphastar_i(alpha: float, Mstar: float, M_i: float) -> float: ...
def mcpl_statsum_validate(comment: str) -> str: ...
def mcpl_statsum_comment(key: str, value: float) -> str: ...

@final
class Cusum:
    """One-sided upper Page CUSUM change detector with Welford statistics."""
    def __init__(
        self, ref_shift_k: float = 0.5, alarm_h: float = 4.0, startup: int = 10
    ) -> None: ...
    def update(self, x: float) -> bool: ...
    def status(self) -> bool: ...
    def statistic(self) -> float: ...
    def count(self) -> int: ...
    def mean(self) -> float: ...
    def variance(self) -> float: ...
    def std(self) -> float: ...
    def reset(self) -> None: ...

def emit_cards(
    comp: dict[str, float],
    name: str,
    density: float | None = None,
    mcnp_number: int = 1,
    xs_suffix: str = "80c",
    serpent_lib: str = "03c",
    fluka_fid: int = 1,
    partisn_zone: int = 1,
) -> dict[str, str]: ...
def emit_drift_table(
    comp: dict[str, float],
    name: str,
    density: float | None = None,
    mcnp_number: int = 1,
    xs_suffix: str = "80c",
    serpent_lib: str = "03c",
    fluka_fid: int = 1,
    partisn_zone: int = 1,
) -> list[dict[str, Any]]: ...
def emit_armi_cards(
    comp: dict[str, float],
    name: str,
    density: float | None = None,
    mcnp_number: int = 1,
    xs_suffix: str = "80c",
    serpent_lib: str = "03c",
    fluka_fid: int = 1,
    partisn_zone: int = 1,
) -> dict[str, str]: ...
def emit_armi_drift_table(
    comp: dict[str, float],
    name: str,
    density: float | None = None,
    mcnp_number: int = 1,
    xs_suffix: str = "80c",
    serpent_lib: str = "03c",
    fluka_fid: int = 1,
    partisn_zone: int = 1,
) -> list[dict[str, Any]]: ...
def version() -> str: ...
