from collections.abc import Sequence
from typing import Any, final

@final
class Nuclide:
    """A nuclide identifier with naming-convention conversions."""

    def __init__(self, name: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def nucid(self) -> int: ...
    @property
    def zzaaam(self) -> int: ...
    @property
    def z(self) -> int: ...
    @property
    def a(self) -> int: ...
    @property
    def state(self) -> int: ...
    @property
    def zaid(self) -> int: ...
    @property
    def zzllaaam(self) -> str: ...
    @property
    def serpent(self) -> str: ...
    @property
    def nist(self) -> str: ...
    @property
    def cinder(self) -> int: ...
    @property
    def alara(self) -> str: ...
    @property
    def sza(self) -> int: ...
    @property
    def mass(self) -> float | None: ...
    @property
    def abundance(self) -> float | None: ...
    def fluka(self) -> str: ...

@final
class Particle:
    """A particle species with cross-code name translations."""

    def __init__(self, spec: str | int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def describe(self) -> str: ...
    def mcnp(self) -> str | None: ...
    def mcnp6(self) -> str | None: ...
    def fluka(self) -> str | None: ...
    def geant4(self) -> str | None: ...

@final
class XsdirTable:
    """One xsdir directory entry."""
    @property
    def name(self) -> str: ...
    @property
    def awr(self) -> float: ...
    @property
    def filename(self) -> str: ...
    @property
    def filetype(self) -> int: ...
    @property
    def address(self) -> int: ...
    @property
    def tablelength(self) -> int: ...
    @property
    def temperature(self) -> float | None: ...
    @property
    def ptable(self) -> bool: ...
    def zaid(self) -> str: ...
    def to_serpent(self, directory: str = "") -> str: ...

@final
class Xsdir:
    """Parsed MCNP xsdir cross-section index."""
    @property
    def datapath(self) -> str | None: ...
    @property
    def awr(self) -> dict[int, float]: ...
    @property
    def tables(self) -> list[XsdirTable]: ...
    def find_table(self, name: str) -> list[XsdirTable]: ...
    def nucs(self) -> list[int]: ...

@final
class MeshTally:
    """One fmesh4 tally from a meshtal file."""
    @property
    def tally_number(self) -> int: ...
    @property
    def particle(self) -> str: ...
    @property
    def dose_response(self) -> bool: ...
    @property
    def x_bounds(self) -> list[float]: ...
    @property
    def y_bounds(self) -> list[float]: ...
    @property
    def z_bounds(self) -> list[float]: ...
    @property
    def e_bounds(self) -> list[float]: ...
    @property
    def result(self) -> list[list[float]]: ...
    @property
    def rel_error(self) -> list[list[float]]: ...
    @property
    def total_result(self) -> list[float]: ...
    def dims(self) -> tuple[int, int, int]: ...
    def num_ves(self) -> int: ...
    def num_e_groups(self) -> int: ...
    def cell(self, i: int, j: int, k: int) -> tuple[list[float], list[float]]: ...
    def cell_total(self, i: int, j: int, k: int) -> tuple[float, float]: ...

@final
class Meshtal:
    """Parsed MCNP meshtal file."""
    @property
    def version(self) -> str: ...
    @property
    def ld(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def histories(self) -> int: ...
    @property
    def tallies(self) -> dict[int, MeshTally]: ...

@final
class Wwinp:
    """Parsed MCNP WWINP weight-window file (Cartesian)."""
    @property
    def ni(self) -> int: ...
    @property
    def nr(self) -> int: ...
    @property
    def ne(self) -> list[int]: ...
    @property
    def nf(self) -> tuple[int, int, int]: ...
    @property
    def origin(self) -> tuple[float, float, float]: ...
    @property
    def nc(self) -> tuple[int, int, int]: ...
    @property
    def cm(self) -> list[list[float]]: ...
    @property
    def bounds(self) -> list[list[float]]: ...
    @property
    def e(self) -> list[list[float]]: ...
    def ww_row(self, particle: int, group: int) -> list[float]: ...
    def ww_column(self, particle: int, ve: int) -> list[float]: ...

@final
class Mctal:
    """Parsed MCNP MCTAL kcode data (upstream subset)."""
    @property
    def code_name(self) -> str: ...
    @property
    def comment(self) -> str: ...
    @property
    def n_histories(self) -> int: ...
    @property
    def n_cycles(self) -> int: ...
    @property
    def n_inactive(self) -> int: ...
    @property
    def vars_per_cycle(self) -> int: ...
    @property
    def k_col(self) -> list[float]: ...
    @property
    def k_abs(self) -> list[float]: ...
    @property
    def k_path(self) -> list[float]: ...
    @property
    def prompt_life_col(self) -> list[float]: ...
    @property
    def prompt_life_path(self) -> list[float]: ...
    @property
    def averages(self) -> list[dict[str, float]]: ...

@final
class SurfSrc:
    """Parsed MCNP SSW surface-source file."""
    @property
    def kod(self) -> str: ...
    @property
    def ver(self) -> str: ...
    @property
    def np1(self) -> int: ...
    @property
    def nrss(self) -> int: ...
    @property
    def ncrd(self) -> int: ...
    @property
    def njsw(self) -> int: ...
    @property
    def niss(self) -> int: ...
    def print_header(self) -> str: ...
    def tracks(self) -> list[dict[str, float]]: ...

@final
class Chain:
    """Parsed depletion chain (XML format)."""
    @property
    def nuclides(self) -> list[str]: ...
    def index_of(self, name: str) -> int | None: ...

@final
class Cascade:
    """Enrichment cascade with numeric multicomponent solving."""
    @staticmethod
    def default_uranium() -> Cascade: ...
    def solve(self, tolerance: float | None = None, max_iterations: int | None = None) -> None: ...
    @property
    def swu_per_feed(self) -> float: ...
    @property
    def swu_per_prod(self) -> float: ...
    @property
    def x_prod_j(self) -> float: ...
    @property
    def x_tail_j(self) -> float: ...
    def separative_work_per_product(self) -> float: ...

@final
class MaterialsCompendium:
    """PNNL/DOE Materials Compendium (411 named materials)."""
    @staticmethod
    def load(path: str) -> MaterialsCompendium: ...
    def __len__(self) -> int: ...
    def names(self) -> list[str]: ...
    def get(self, name: str, as_material: bool = False) -> dict[str, Any] | None: ...

@final
class UsrbinTally:
    """One FLUKA USRBIN detector."""
    @property
    def name(self) -> str: ...
    @property
    def particle(self) -> str: ...
    @property
    def nx(self) -> int: ...
    @property
    def ny(self) -> int: ...
    @property
    def nz(self) -> int: ...
    @property
    def x_bounds(self) -> list[float]: ...
    @property
    def y_bounds(self) -> list[float]: ...
    @property
    def z_bounds(self) -> list[float]: ...
    @property
    def data(self) -> list[float]: ...
    @property
    def error(self) -> list[float]: ...
    def dims(self) -> tuple[int, int, int]: ...

@final
class MagicOutput:
    """MAGIC weight-window generation output."""
    @property
    def lower_bounds_ww(self) -> list[float]: ...
    @property
    def groups_per_ve(self) -> int: ...
    @property
    def scale_factors(self) -> list[float]: ...
    @property
    def e_upper_bounds(self) -> list[float]: ...
    @property
    def ww_tag_name(self) -> str: ...

@final
class AliasTable:
    """Walker alias table for discrete sampling."""
    def __init__(self, pdf: list[float]) -> None: ...
    def sample(self, r1: float, r2: float) -> int: ...
    @property
    def pdf(self) -> list[float]: ...
    def __len__(self) -> int: ...

@final
class MeshSourceSampler:
    """Mesh source sampler over a meshtal tally (analog/uniform/user)."""
    def __init__(
        self, tally: MeshTally, mode: str, user_pdf: list[float] | None = None
    ) -> None: ...
    def sample(self, r1: float, r2: float) -> dict[str, float]: ...

@final
class PtracFile:
    """Parsed MCNP PTRAC event file."""
    @property
    def problem_title(self) -> str: ...
    @property
    def width_code(self) -> int: ...
    @property
    def variable_nums(self) -> dict[str, int]: ...
    def events(self) -> list[dict[str, float]]: ...

def from_zaid(zaid: int) -> Nuclide: ...
def atomic_mass(key: int | str) -> float | None: ...
def natural_abundance(key: int | str) -> float | None: ...
def rxname_id(name: str) -> int: ...
def rxname_name(id: int) -> str | None: ...
def rxname_mt(id: int) -> int: ...
def read_xsdir(path: str) -> Xsdir: ...
def read_meshtal(path: str) -> Meshtal: ...
def read_wwinp(path: str) -> Wwinp: ...
def read_mctal(path: str) -> Mctal: ...
def read_ssw(path: str) -> SurfSrc: ...
def read_ptrac(path: str) -> PtracFile: ...
def half_life(key: int | str) -> float | None: ...
def decay_constant(key: int | str) -> float | None: ...
def q_value_capture(key: int | str) -> float | None: ...
def q_value_alpha(key: int | str) -> float | None: ...
def read_inp(path: str) -> list[dict[str, Any]]: ...
def from_formula(formula: str) -> dict[str, float]: ...
def activity(comp: dict[str, float]) -> dict[str, float]: ...
def read_serpent(path: str, kind: str) -> dict[str, Any]: ...
def read_usrbin(path: str) -> list[UsrbinTally]: ...
def magic(tally: MeshTally, per_group: bool = False, tolerance: float = 0.5) -> MagicOutput: ...
def write_ssw(ssw: SurfSrc, path: str, tracks: list[dict[str, float]] | None = None) -> None: ...
def mesh_to_geom(
    x_bounds: Sequence[float],
    y_bounds: Sequence[float],
    z_bounds: Sequence[float],
    cell_materials: Sequence[tuple[str, float] | None],
    title_card: str,
) -> str: ...
def read_chain(path: str) -> Chain: ...
def deplete(
    chain: Chain,
    n0: dict[str, float],
    dt: float,
    rates: dict[str, float] | None = None,
    order: int = 48,
) -> dict[str, float]: ...
def version() -> str: ...
