[package]
name = "nucleide-bindings"
description = "PyO3 bindings exposing Nucleide to Python as nucleide._internal"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "nucleide_bindings"
crate-type = ["cdylib"]

[dependencies]
pyo3.workspace = true
nucleide-nuclei.workspace = true
nucleide-material.workspace = true
nucleide-mcnp-io.workspace = true
nucleide-depletion = { workspace = true, default-features = true }
nucleide-serpent-io.workspace = true
nucleide-fluka-io.workspace = true
nucleide-vr-tools.workspace = true
nucleide-enrichment.workspace = true
nucleide-alara-io.workspace = true
nucleide-cccc-io.workspace = true
nucleide-fispact-io.workspace = true
nucleide-origen-io.workspace = true
nucleide-r2s.workspace = true
