[package]
name = "vr-tools"
description = "placeholder"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
mcnp-io.workspace = true

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "vr_tools_bench"
harness = false
