[package]
name = "enrichment"
description = "Multicomponent enrichment cascades and SWU analytics"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
nuclei.workspace = true

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "enrichment_bench"
harness = false
