//! Multi-step depletion integrators with activity and decay-heat results.
//!
//! Single-step CRAM ([`crate::cram`]) evaluates `exp(A*dt)` exactly for a
//! fixed transmutation matrix. This module chains steps with prescribed
//! per-step one-group rates and records decay observables at every node:
//!
//! - activity `A_i = λ_i N_i` [Bq] from the chain decay constants, and
//! - decay heat `H_i = λ_i N_i E_i` [W] with `E_i` in joule
//!   (`E[MeV] * MEV_TO_JOULE`).
//!
//! # Integrators
//!
//! - [`Integrator::Predictor`]: one CRAM solve per step with the step's
//!   matrix `A_k`.
//! - [`Integrator::Cecm`]: predictor + corrector average (2 CRAM solves per
//!   step). The corrector re-solves from the step start with the averaged
//!   matrix `(A_BOS + A_EOS)/2`. Because rates here are prescribed (not
//!   flux-renormalized from the predicted composition), `A_EOS == A_BOS`
//!   and the corrector reproduces the predictor up to roundoff; the
//!   two-solve structure is kept so flux-coupled extensions can plug a
//!   recomputed `A_EOS` into the same code path.
//! - [`Integrator::Cf4`]: 4th-order commutator-free quasi-Magnus propagator
//!   (Blanes–Casas–Thalhammer: two exponentials over Gauss–Legendre nodes)
//!   with stage coefficients `a11 = a22 = 1/4 + √3/6`,
//!   `a12 = a21 = 1/4 − √3/6`. Under the piecewise-constant rate
//!   reconstruction used here (one rate set per step) both nodes see the
//!   same matrix (`A1 == A2 == A_k`), so each stage is a half-step
//!   exponential `exp(A_k dt/2)` and the step composes two half-step CRAM
//!   solves. Halving the CRAM argument can only help the rational
//!   approximation, hence CF4 accuracy is >= Predictor accuracy on the
//!   analytic test chain (asserted in the `cf4_matches_or_beats_predictor`
//!   test). The coefficient structure is applied explicitly so the code
//!   path generalizes to interpolated nodal matrices for time-varying
//!   rates.
//!
//! # Decay energies
//!
//! [`decay_energy_mev`] resolves the per-nuclide decay energy in MeV with
//! the following precedence:
//!
//! 1. the chain's `decay_energy` attribute (stored in eV on
//!    [`ChainNuclide`](crate::chain::ChainNuclide), converted to MeV) when
//!    positive and finite;
//! 2. the ENDF/B-VII.1 prompt-decay-energy table
//!    (`nucleide_nuclei::data::decay_energy_mev_by_name`, generated by
//!    `scripts/gen-nuclear-data.py`);
//! 3. `0.0` otherwise (documented zero-heat behavior, e.g. stable nuclides
//!    and synthetic test nuclides).
//!
//! A single evaluated table is the only source of truth — there is no
//! parallel hand-kept fallback. No HDF5 dependencies are involved.

use crate::chain::{Chain, ChainNuclide, Error};
use crate::cram::Order;
use crate::matrix::{DepletionSystem, ReactionRates};

/// Joule per MeV (exact CODATA factor `1.602176634e-13`, here truncated to
/// the `1.602e-13` value used across the depletion API).
pub const MEV_TO_JOULE: f64 = 1.602e-13;

/// EV per MeV.
pub const EV_PER_MEV: f64 = 1.0e6;

/// Time-series integrator selector.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Integrator {
    /// One CRAM solve per step.
    Predictor,
    /// Predictor + corrector average (2 CRAM solves per step).
    Cecm,
    /// 4th-order commutator-free propagator (2 CRAM half-step solves).
    Cf4,
}

/// One depletion step: fixed length plus prescribed one-group rates.
///
/// `rates` uses the same [`ReactionRates`] layout as
/// [`DepletionSystem::build`] (`nuclide_index → (reaction_name → rate
/// [1/s])`); missing entries contribute zero.
#[derive(Debug, Clone, Default)]
pub struct Step {
    /// Step length [s]; must be positive and finite.
    pub dt: f64,
    /// One-group reaction rates active during this step [1/s].
    pub rates: ReactionRates,
}

impl Step {
    /// Build a step from a length and a rate map.
    pub fn new(dt: f64, rates: ReactionRates) -> Self {
        Self { dt, rates }
    }
}

/// Time-series result: one row per time node in chain-nuclide order.
///
/// `times[0] == 0.0` and the first row of each series is the initial
/// state, so every series has `steps.len() + 1` rows. `activity` rows are
/// in Bq and `decay_heat` rows in W; both are clamped at zero (CRAM can
/// return tiny negative densities for fully depleted nuclides) while
/// `atoms` rows are left unclamped and exact.
#[derive(Debug, Clone, PartialEq)]
pub struct TimeSeries {
    /// Cumulative time nodes [s], starting at 0.0.
    pub times: Vec<f64>,
    /// Atom counts per node in chain order.
    pub atoms: Vec<Vec<f64>>,
    /// Activity per node in chain order [Bq].
    pub activity: Vec<Vec<f64>>,
    /// Decay heat per node in chain order [W].
    pub decay_heat: Vec<Vec<f64>>,
}

impl TimeSeries {
    /// Number of time nodes (steps + 1).
    pub fn len(&self) -> usize {
        self.times.len()
    }

    /// Whether the series holds no nodes (only possible when built empty).
    pub fn is_empty(&self) -> bool {
        self.times.is_empty()
    }

    /// Number of nuclides per row.
    pub fn nuclides(&self) -> usize {
        self.atoms.first().map_or(0, Vec::len)
    }
}

/// Resolve one nuclide's decay energy in MeV: chain `decay_energy` (eV →
/// MeV) when positive and finite, else the ENDF/B-VII.1 prompt table
/// (`nucleide_nuclei::data`), else `0.0`.
pub fn decay_energy_mev(nuc: &ChainNuclide) -> f64 {
    if nuc.decay_energy > 0.0 && nuc.decay_energy.is_finite() {
        return nuc.decay_energy / EV_PER_MEV;
    }
    nucleide_nuclei::data::decay_energy_mev_by_name(&nuc.name).unwrap_or(0.0)
}

/// Per-nuclide decay energies keyed by chain-nuclide name [MeV].
///
/// Single resolution point shared by [`integrate`] and the Python
/// `deplete_series` heat channel, so both report identical heats.
pub fn decay_energies_by_name(chain: &Chain) -> std::collections::BTreeMap<String, f64> {
    chain
        .nuclides
        .iter()
        .map(|nuc| (nuc.name.clone(), decay_energy_mev(nuc)))
        .collect()
}

/// Per-nuclide decay energies in chain order [MeV] (see [`decay_energy_mev`]).
pub fn decay_energies_mev(sys: &DepletionSystem) -> Vec<f64> {
    sys.chain.nuclides.iter().map(decay_energy_mev).collect()
}

/// Per-nuclide decay constants in chain order [1/s].
///
/// Invalid half-lives cannot occur here ( [`DepletionSystem::build`] already
/// rejects them), so any error resolves to `0.0`.
pub fn decay_constants(sys: &DepletionSystem) -> Vec<f64> {
    sys.chain
        .nuclides
        .iter()
        .map(|n| n.decay_constant().unwrap_or(0.0))
        .collect()
}

/// Activity vector `A_i = λ_i N_i` [Bq] in chain order, clamped at zero.
pub fn activity_vec(sys: &DepletionSystem, nvec: &[f64]) -> Vec<f64> {
    assert_eq!(
        nvec.len(),
        sys.chain.len(),
        "nvec length {} != chain size {}",
        nvec.len(),
        sys.chain.len()
    );
    decay_constants(sys)
        .iter()
        .zip(nvec)
        .map(|(lam, n)| (lam * n).max(0.0))
        .collect()
}

/// Decay-heat vector `H_i = λ_i N_i E_i * MEV_TO_JOULE` [W] in chain
/// order, clamped at zero. `energies` holds per-nuclide decay energies in
/// MeV (see [`decay_energies_mev`]) and must match the chain length.
pub fn decay_heat_vec(sys: &DepletionSystem, nvec: &[f64], energies: &[f64]) -> Vec<f64> {
    assert_eq!(
        nvec.len(),
        sys.chain.len(),
        "nvec length {} != chain size {}",
        nvec.len(),
        sys.chain.len()
    );
    assert_eq!(
        energies.len(),
        sys.chain.len(),
        "energies length {} != chain size {}",
        energies.len(),
        sys.chain.len()
    );
    decay_constants(sys)
        .iter()
        .zip(nvec)
        .zip(energies)
        .map(|((lam, n), e)| (lam * n * e * MEV_TO_JOULE).max(0.0))
        .collect()
}

/// CF4 stage coefficients (Blanes–Casas–Thalhammer commutator-free
/// quasi-Magnus, `a11 = a22 = 1/4 + √3/6`, `a12 = a21 = 1/4 − √3/6`).
const CF4_A11: f64 = 0.538_675_134_594_812_9; // 1/4 + sqrt(3)/6
const CF4_A12: f64 = -0.038_675_134_594_812_87; // 1/4 - sqrt(3)/6

/// Integrate a prescribed-rate schedule with the chosen method.
///
/// `sys` supplies the chain template (its baked rates are *not* used; each
/// step's [`Step::rates`] rebuilds the matrix, so time-varying rates are
/// handled exactly per step). `n0` is in chain order. Returns the full
/// [`TimeSeries`] including the `t = 0` initial row.
///
/// Errors on dimension mismatch, non-positive/non-finite step lengths, or
/// CRAM backend failures (mapped to [`Error::BadStructure`], matching
/// [`crate::deplete`]).
pub fn integrate(
    sys: &DepletionSystem,
    n0: &[f64],
    steps: &[Step],
    integrator: Integrator,
    order: Order,
) -> Result<TimeSeries, Error> {
    if n0.len() != sys.chain.len() {
        return Err(Error::BadStructure(format!(
            "n0 length {} != chain size {}",
            n0.len(),
            sys.chain.len()
        )));
    }
    for (k, step) in steps.iter().enumerate() {
        if step.dt <= 0.0 || !step.dt.is_finite() {
            return Err(Error::BadStructure(format!(
                "invalid timestep dt at step {k}: {}",
                step.dt
            )));
        }
    }

    let energies = decay_energies_mev(sys);
    let mut times = Vec::with_capacity(steps.len() + 1);
    let mut atoms = Vec::with_capacity(steps.len() + 1);
    let mut activity = Vec::with_capacity(steps.len() + 1);
    let mut decay_heat = Vec::with_capacity(steps.len() + 1);

    times.push(0.0);
    atoms.push(n0.to_vec());
    activity.push(activity_vec(sys, n0));
    decay_heat.push(decay_heat_vec(sys, n0, &energies));

    let mut n = n0.to_vec();
    let mut t = 0.0;
    for step in steps {
        n = advance(sys, &n, step, integrator, order)?;
        t += step.dt;
        times.push(t);
        activity.push(activity_vec(sys, &n));
        decay_heat.push(decay_heat_vec(sys, &n, &energies));
        atoms.push(n.clone());
    }

    Ok(TimeSeries {
        times,
        atoms,
        activity,
        decay_heat,
    })
}

/// Advance one step with the chosen integrator.
fn advance(
    sys: &DepletionSystem,
    n: &[f64],
    step: &Step,
    integrator: Integrator,
    order: Order,
) -> Result<Vec<f64>, Error> {
    let mat = || DepletionSystem::build(sys.chain.clone(), &step.rates);
    match integrator {
        Integrator::Predictor => {
            let sys_k = mat()?;
            crate::cram(&sys_k, order, n, step.dt).map_err(|e| Error::BadStructure(e.to_string()))
        }
        Integrator::Cecm => {
            // Predictor with BOS rates, then corrector with the averaged
            // (BOS + EOS) / 2 matrix. Prescribed rates make EOS == BOS, so
            // the average reuses the same matrix (midpoint rate reuse); the
            // second CRAM keeps the two-solve CECM structure for future
            // flux-coupled EOS rates.
            let sys_k = mat()?;
            let _pred = crate::cram(&sys_k, order, n, step.dt)
                .map_err(|e| Error::BadStructure(e.to_string()))?;
            // EOS rates equal BOS rates here; average is `sys_k` itself.
            crate::cram(&sys_k, order, n, step.dt).map_err(|e| Error::BadStructure(e.to_string()))
        }
        Integrator::Cf4 => {
            // Two-exponential CF4: stage weights s1 = a11 + a12 and
            // s2 = a21 + a22 (both 1/2 with the coefficients above) scale
            // the stage matrices; with A1 == A2 == A_k each stage is a
            // half-step solve.
            let sys_k = mat()?;
            let s1 = CF4_A11 + CF4_A12;
            let s2 = CF4_A12 + CF4_A11;
            let stage1 = scaled_system(&sys_k, s1);
            let n1 = crate::cram(&stage1, order, n, step.dt)
                .map_err(|e| Error::BadStructure(e.to_string()))?;
            let stage2 = scaled_system(&sys_k, s2);
            crate::cram(&stage2, order, &n1, step.dt)
                .map_err(|e| Error::BadStructure(e.to_string()))
        }
    }
}

/// Clone a system with all matrix entries scaled by `scale`
/// (used for CF4 half-step stages; pattern and diagonal layout are kept).
fn scaled_system(sys: &DepletionSystem, scale: f64) -> DepletionSystem {
    let mut out = sys.clone();
    for v in &mut out.base_values {
        *v *= scale;
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::chain::{Chain, ChainNuclide, DecayMode};

    const L1: f64 = 1.0e-6;
    const L2: f64 = 1.0e-5;

    fn abc_chain() -> Chain {
        let a = ChainNuclide {
            name: "A".into(),
            half_life: Some(std::f64::consts::LN_2 / L1),
            decay_modes: vec![DecayMode {
                kind: "beta".into(),
                target: "B".into(),
                branching_ratio: 1.0,
            }],
            ..Default::default()
        };
        let b = ChainNuclide {
            name: "B".into(),
            half_life: Some(std::f64::consts::LN_2 / L2),
            decay_modes: vec![DecayMode {
                kind: "beta".into(),
                target: "C".into(),
                branching_ratio: 1.0,
            }],
            ..Default::default()
        };
        let c = ChainNuclide {
            name: "C".into(),
            ..Default::default()
        };
        Chain::from_nuclides(vec![a, b, c]).unwrap()
    }

    /// Analytic Bateman solution for A -> B -> C from pure A.
    fn bateman(n0: f64, t: f64) -> [f64; 3] {
        let na = n0 * (-L1 * t).exp();
        let nb = n0 * L1 / (L2 - L1) * ((-L1 * t).exp() - (-L2 * t).exp());
        let nc = n0 - na - nb;
        [na, nb, nc]
    }

    fn constant_steps(dt: f64, count: usize) -> Vec<Step> {
        (0..count)
            .map(|_| Step::new(dt, ReactionRates::new()))
            .collect()
    }

    fn max_rel_err(got: &[f64], want: &[f64]) -> f64 {
        got.iter()
            .zip(want)
            .map(|(g, w)| (g - w).abs() / w.max(1e-30))
            .fold(0.0_f64, f64::max)
    }

    #[test]
    fn predictor_matches_bateman() {
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let n0 = vec![1.0e15, 0.0, 0.0];
        let steps = constant_steps(2.0e4, 5);
        let ts = integrate(&sys, &n0, &steps, Integrator::Predictor, Order::Order48).unwrap();

        assert_eq!(ts.len(), 6);
        assert_eq!(ts.times[0], 0.0);
        assert_eq!(*ts.times.last().unwrap(), 1.0e5);
        // Initial row echoes n0.
        assert_eq!(ts.atoms[0], n0);
        // Every node matches the analytic solution at its cumulative time.
        for (k, t) in ts.times.iter().enumerate() {
            let want = bateman(n0[0], *t);
            let err = max_rel_err(&ts.atoms[k], &want);
            assert!(err < 1e-6, "node {k} t={t}: err {err}");
        }
    }

    #[test]
    fn cecm_matches_bateman() {
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let n0 = vec![1.0e15, 0.0, 0.0];
        let steps = constant_steps(2.0e4, 5);
        let ts = integrate(&sys, &n0, &steps, Integrator::Cecm, Order::Order48).unwrap();

        for (k, t) in ts.times.iter().enumerate() {
            let want = bateman(n0[0], *t);
            let err = max_rel_err(&ts.atoms[k], &want);
            assert!(err < 1e-6, "node {k} t={t}: err {err}");
        }
    }

    #[test]
    fn cf4_matches_or_beats_predictor() {
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let n0 = vec![1.0e15, 0.0, 0.0];
        // Coarse steps with the cheaper order so the CRAM-argument
        // difference between one full step and two half steps is visible.
        let steps = constant_steps(2.0e5, 4);
        let pred = integrate(&sys, &n0, &steps, Integrator::Predictor, Order::Order16).unwrap();
        let cf4 = integrate(&sys, &n0, &steps, Integrator::Cf4, Order::Order16).unwrap();

        let total_t = 8.0e5;
        let want = bateman(n0[0], total_t);
        let pred_err = max_rel_err(pred.atoms.last().unwrap(), &want);
        let cf4_err = max_rel_err(cf4.atoms.last().unwrap(), &want);
        assert!(pred_err < 1e-4, "predictor err {pred_err}");
        assert!(
            cf4_err <= pred_err,
            "cf4 err {cf4_err} should be <= predictor err {pred_err}"
        );
    }

    #[test]
    fn atoms_conserved_along_series() {
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let n0 = vec![1.0e15, 0.0, 0.0];
        let steps = constant_steps(2.0e4, 5);
        for integrator in [Integrator::Predictor, Integrator::Cecm, Integrator::Cf4] {
            let ts = integrate(&sys, &n0, &steps, integrator, Order::Order48).unwrap();
            for (k, row) in ts.atoms.iter().enumerate() {
                let total: f64 = row.iter().sum();
                let err = (total - n0[0]).abs() / n0[0];
                assert!(err < 1e-8, "{integrator:?} node {k}: err {err}");
            }
        }
    }

    #[test]
    fn invalid_dt_rejected() {
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let n0 = vec![1.0e15, 0.0, 0.0];
        for bad in [0.0, -1.0, f64::NAN, f64::INFINITY] {
            let steps = vec![Step::new(bad, ReactionRates::new())];
            assert!(
                integrate(&sys, &n0, &steps, Integrator::Predictor, Order::Order48).is_err(),
                "dt={bad} should fail"
            );
        }
        // Dimension mismatch also fails.
        let steps = constant_steps(1.0, 1);
        assert!(integrate(&sys, &[1.0], &steps, Integrator::Predictor, Order::Order48).is_err());
    }

    #[test]
    fn activity_and_decay_heat_spot_check() {
        let nuc = ChainNuclide {
            name: "Solo".into(),
            half_life: Some(std::f64::consts::LN_2 / L1),
            decay_energy: 2.0e6, // 2 MeV in eV
            ..Default::default()
        };
        let sys = DepletionSystem::build(
            Chain::from_nuclides(vec![nuc]).unwrap(),
            &ReactionRates::new(),
        )
        .unwrap();
        let n = vec![1.0e12];
        let act = activity_vec(&sys, &n);
        assert_eq!(act.len(), 1);
        assert!((act[0] - L1 * 1.0e12).abs() / act[0] < 1e-12);

        let heat = decay_heat_vec(&sys, &n, &decay_energies_mev(&sys));
        let want = L1 * 1.0e12 * 2.0 * MEV_TO_JOULE;
        assert!((heat[0] - want).abs() / want < 1e-12);

        // Chain energy (eV -> MeV) wins over the fallback table.
        assert_eq!(decay_energies_mev(&sys), vec![2.0]);
    }

    #[test]
    fn decay_energy_table_and_zero_behavior() {
        // Unknown synthetic nuclide without chain energy -> 0.0.
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        assert_eq!(decay_energies_mev(&sys), vec![0.0, 0.0, 0.0]);
        let heat = decay_heat_vec(&sys, &[1.0e10, 1.0e10, 1.0e10], &decay_energies_mev(&sys));
        assert_eq!(heat, vec![0.0, 0.0, 0.0]);

        // Real nuclide resolves through the ENDF/B-VII.1 table (Cs137 prompt
        // mean, excluding the Ba137_m1 daughter gamma).
        let chain = Chain::from_nuclides(vec![ChainNuclide {
            name: "Cs137".into(),
            half_life: Some(9.49e8),
            ..Default::default()
        }])
        .unwrap();
        let sys = DepletionSystem::build(chain, &ReactionRates::new()).unwrap();
        let e = decay_energies_mev(&sys)[0];
        assert!((e - 0.1794).abs() / 0.1794 < 0.05, "{e}");
    }

    #[test]
    fn series_carries_activity_and_heat_rows() {
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let n0 = vec![1.0e15, 0.0, 0.0];
        let steps = constant_steps(2.0e4, 3);
        let ts = integrate(&sys, &n0, &steps, Integrator::Predictor, Order::Order48).unwrap();
        assert_eq!(ts.activity.len(), ts.len());
        assert_eq!(ts.decay_heat.len(), ts.len());
        // t = 0 activity is exact: only A is present.
        assert!((ts.activity[0][0] - L1 * n0[0]).abs() / ts.activity[0][0] < 1e-12);
        assert_eq!(ts.activity[0][1], 0.0);
        // Mid-series B activity matches Bateman through the helper.
        let want_b = bateman(n0[0], ts.times[2])[1] * L2;
        assert!((ts.activity[2][1] - want_b).abs() / want_b < 1e-6);
    }
}
