//! Multi-step depletion integrators with activity and decay-heat results.
//!
//! Single-step CRAM ([`crate::cram()`]) evaluates `exp(A*dt)` exactly for a
//! fixed transmutation matrix. This module chains steps with prescribed
//! per-step one-group rates and records decay observables at every node:
//!
//! - activity `A_i = λ_i N_i` \[Bq\] from the chain decay constants, and
//! - decay heat `H_i = λ_i N_i E_i` \[W\] with `E_i` in joule
//!   (`E[MeV] * MEV_TO_JOULE`).
//!
//! # Integrators
//!
//! - [`Integrator::Predictor`]: one CRAM solve per step with the step's
//!   matrix `A_k`.
//! - [`Integrator::Cecm`]: predictor + corrector average (2 CRAM solves per
//!   step). The corrector re-solves from the step start with the averaged
//!   matrix `(A_BOS + A_EOS)/2`. Because rates here are prescribed (not
//!   flux-renormalized from the predicted composition), `A_EOS == A_BOS`
//!   and the corrector reproduces the predictor up to roundoff; the
//!   two-solve structure is kept so flux-coupled extensions can plug a
//!   recomputed `A_EOS` into the same code path.
//! - [`Integrator::Cf4`]: 4th-order commutator-free quasi-Magnus propagator
//!   (Blanes–Casas–Thalhammer: two exponentials over Gauss–Legendre nodes)
//!   with stage coefficients `a11 = a22 = 1/4 + √3/6`,
//!   `a12 = a21 = 1/4 − √3/6`. Under the piecewise-constant rate
//!   reconstruction used here (one rate set per step) both nodes see the
//!   same matrix (`A1 == A2 == A_k`), so each stage is a half-step
//!   exponential `exp(A_k dt/2)` and the step composes two half-step CRAM
//!   solves. Halving the CRAM argument can only help the rational
//!   approximation, hence CF4 accuracy is >= Predictor accuracy on the
//!   analytic test chain (asserted in the `cf4_matches_or_beats_predictor`
//!   test). The coefficient structure is applied explicitly so the code
//!   path generalizes to interpolated nodal matrices for time-varying
//!   rates.
//!
//! # Decay energies
//!
//! [`decay_energy_mev`] resolves the per-nuclide decay energy in MeV with
//! the following precedence:
//!
//! 1. the chain's `decay_energy` attribute (stored in eV on
//!    [`ChainNuclide`], converted to MeV) when
//!    positive and finite;
//! 2. the ENDF/B-VII.1 prompt-decay-energy table
//!    (`nucleide_nuclei::data::decay_energy_mev_by_name`, generated by
//!    `scripts/gen-nuclear-data.py`);
//! 3. `0.0` otherwise (documented zero-heat behavior, e.g. stable nuclides
//!    and synthetic test nuclides).
//!
//! A single evaluated table is the only source of truth — there is no
//! parallel hand-kept fallback. No HDF5 dependencies are involved.

use crate::bateman::{BatemanCache, Method};
use crate::chain::{Chain, ChainNuclide, Error};
use crate::cram::Order;
use crate::matrix::{DepletionSystem, ReactionRates};

/// Joule per MeV (exact CODATA factor `1.602176634e-13`, here truncated to
/// the `1.602e-13` value used across the depletion API).
pub const MEV_TO_JOULE: f64 = 1.602e-13;

/// EV per MeV.
pub const EV_PER_MEV: f64 = 1.0e6;

/// Time-series integrator selector.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Integrator {
    /// One CRAM solve per step.
    Predictor,
    /// Predictor + corrector average (2 CRAM solves per step).
    Cecm,
    /// 4th-order commutator-free propagator (2 CRAM half-step solves).
    Cf4,
}

/// One depletion step: fixed length plus prescribed one-group rates.
///
/// `rates` uses the same [`ReactionRates`] layout as
/// [`DepletionSystem::build`] (`nuclide_index → (reaction_name → rate
/// [1/s])`); missing entries contribute zero.
#[derive(Debug, Clone, Default)]
pub struct Step {
    /// Step length \[s\]; must be positive and finite.
    pub dt: f64,
    /// One-group reaction rates active during this step [1/s].
    pub rates: ReactionRates,
}

impl Step {
    /// Build a step from a length and a rate map.
    pub fn new(dt: f64, rates: ReactionRates) -> Self {
        Self { dt, rates }
    }
}

/// Time-series result: one row per time node in chain-nuclide order.
///
/// `times[0] == 0.0` and the first row of each series is the initial
/// state, so every series has `steps.len() + 1` rows. `activity` rows are
/// in Bq and `decay_heat` rows in W; both are clamped at zero (CRAM can
/// return tiny negative densities for fully depleted nuclides) while
/// `atoms` rows are left unclamped and exact.
#[derive(Debug, Clone, PartialEq)]
pub struct TimeSeries {
    /// Cumulative time nodes \[s\], starting at 0.0.
    pub times: Vec<f64>,
    /// Atom counts per node in chain order.
    pub atoms: Vec<Vec<f64>>,
    /// Activity per node in chain order \[Bq\].
    pub activity: Vec<Vec<f64>>,
    /// Decay heat per node in chain order \[W\].
    pub decay_heat: Vec<Vec<f64>>,
}

impl TimeSeries {
    /// Number of time nodes (steps + 1).
    pub fn len(&self) -> usize {
        self.times.len()
    }

    /// Whether the series holds no nodes (only possible when built empty).
    pub fn is_empty(&self) -> bool {
        self.times.is_empty()
    }

    /// Number of nuclides per row.
    pub fn nuclides(&self) -> usize {
        self.atoms.first().map_or(0, Vec::len)
    }
}

/// Resolve one nuclide's decay energy in MeV: chain `decay_energy` (eV →
/// MeV) when positive and finite, else the ENDF/B-VII.1 prompt table
/// (`nucleide_nuclei::data`), else `0.0`.
pub fn decay_energy_mev(nuc: &ChainNuclide) -> f64 {
    if nuc.decay_energy > 0.0 && nuc.decay_energy.is_finite() {
        return nuc.decay_energy / EV_PER_MEV;
    }
    nucleide_nuclei::data::decay_energy_mev_by_name(&nuc.name).unwrap_or(0.0)
}

/// Per-nuclide decay energies keyed by chain-nuclide name \[MeV\].
///
/// Single resolution point shared by [`integrate`] and the Python
/// `deplete_series` heat channel, so both report identical heats.
pub fn decay_energies_by_name(chain: &Chain) -> std::collections::BTreeMap<String, f64> {
    chain
        .nuclides
        .iter()
        .map(|nuc| (nuc.name.clone(), decay_energy_mev(nuc)))
        .collect()
}

/// Per-nuclide decay energies in chain order \[MeV\] (see [`decay_energy_mev`]).
pub fn decay_energies_mev(sys: &DepletionSystem) -> Vec<f64> {
    sys.chain.nuclides.iter().map(decay_energy_mev).collect()
}

/// Per-nuclide decay constants in chain order [1/s].
///
/// Invalid half-lives cannot occur here ( [`DepletionSystem::build`] already
/// rejects them), so any error resolves to `0.0`.
pub fn decay_constants(sys: &DepletionSystem) -> Vec<f64> {
    sys.chain
        .nuclides
        .iter()
        .map(|n| n.decay_constant().unwrap_or(0.0))
        .collect()
}

/// Activity vector `A_i = λ_i N_i` \[Bq\] in chain order, clamped at zero.
pub fn activity_vec(sys: &DepletionSystem, nvec: &[f64]) -> Vec<f64> {
    assert_eq!(
        nvec.len(),
        sys.chain.len(),
        "nvec length {} != chain size {}",
        nvec.len(),
        sys.chain.len()
    );
    decay_constants(sys)
        .iter()
        .zip(nvec)
        .map(|(lam, n)| (lam * n).max(0.0))
        .collect()
}

/// Decay-heat vector `H_i = λ_i N_i E_i * MEV_TO_JOULE` \[W\] in chain
/// order, clamped at zero. `energies` holds per-nuclide decay energies in
/// MeV (see [`decay_energies_mev`]) and must match the chain length.
pub fn decay_heat_vec(sys: &DepletionSystem, nvec: &[f64], energies: &[f64]) -> Vec<f64> {
    assert_eq!(
        nvec.len(),
        sys.chain.len(),
        "nvec length {} != chain size {}",
        nvec.len(),
        sys.chain.len()
    );
    assert_eq!(
        energies.len(),
        sys.chain.len(),
        "energies length {} != chain size {}",
        energies.len(),
        sys.chain.len()
    );
    decay_constants(sys)
        .iter()
        .zip(nvec)
        .zip(energies)
        .map(|((lam, n), e)| (lam * n * e * MEV_TO_JOULE).max(0.0))
        .collect()
}

/// CF4 stage coefficients (Blanes–Casas–Thalhammer commutator-free
/// quasi-Magnus, `a11 = a22 = 1/4 + √3/6`, `a12 = a21 = 1/4 − √3/6`).
const CF4_A11: f64 = 0.538_675_134_594_812_9; // 1/4 + sqrt(3)/6
const CF4_A12: f64 = -0.038_675_134_594_812_87; // 1/4 - sqrt(3)/6

/// Integrate a prescribed-rate schedule with the chosen method.
///
/// `sys` supplies the chain template (its baked rates are *not* used; each
/// step's [`Step::rates`] rebuilds the matrix, so time-varying rates are
/// handled exactly per step). `n0` is in chain order. `method` selects the
/// exponential kernel: [`Method::Cram`] runs IPF CRAM, [`Method::Bateman`] /
/// [`Method::BatemanHp`] run the analytic closed form per step (steps whose
/// matrix carries reaction/fission contributions fall back to CRAM-48 —
/// Bateman is a decay-only fast path). Returns the full [`TimeSeries`]
/// including the `t = 0` initial row.
///
/// Errors on dimension mismatch, non-positive/non-finite step lengths, or
/// backend failures (mapped to [`Error::BadStructure`], matching
/// [`crate::deplete`]).
///
/// # Cross-step reuse
///
/// Expensive time-independent objects are hoisted out of the per-step loop
/// and reused while the step sequence allows it (see [`ReuseStats`]):
///
/// - the [`DepletionSystem`] pattern/entries are reused; only `base_values`
///   are recomputed per step ([`DepletionSystem::refresh_rates`]);
/// - the [`nucleide_linalg::SymbolicLu`] analysis is rebuilt only when the
///   sparsity pattern changes (constant-rate series build it once);
/// - one [`BatemanCache`] is reused for decay-only step sequences whose
///   matrix values are unchanged (the cache holds time-independent `C`/`C⁻¹`;
///   only the `e^{−λdt}` diagonal is fresh per step).
///
/// All reuse checks are exact (entry-by-entry pattern comparison, bit-exact
/// value comparison), so reused results are bit-identical to fresh per-step
/// builds.
pub fn integrate_with_method(
    sys: &DepletionSystem,
    n0: &[f64],
    steps: &[Step],
    integrator: Integrator,
    method: Method,
) -> Result<TimeSeries, Error> {
    let mut stats = ReuseStats::default();
    integrate_with_method_counted(sys, n0, steps, integrator, method, &mut stats)
}

/// Counts of expensive per-series rebuilds observed while integrating one
/// rate schedule.
///
/// [`integrate_with_method`] hoists every time-independent object out of the
/// per-step loop; [`integrate_with_method_counted`] additionally fills this
/// struct so regression tests can prove the reuse (a single build for
/// step-invariant series) while the series stays bit-identical to fresh
/// per-step builds.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ReuseStats {
    /// Number of steps advanced.
    pub steps: usize,
    /// Full [`DepletionSystem`] (pattern + entries) builds.
    pub system_builds: usize,
    /// [`nucleide_linalg::SymbolicLu`] analyses built.
    pub symbolic_builds: usize,
    /// [`BatemanCache`] build attempts (decay probes, including ones that
    /// fall back to CRAM-48).
    pub bateman_builds: usize,
}

/// [`integrate_with_method`] with reuse accounting (see [`ReuseStats`]).
/// Validation and numerics are identical to [`integrate_with_method`].
pub fn integrate_with_method_counted(
    sys: &DepletionSystem,
    n0: &[f64],
    steps: &[Step],
    integrator: Integrator,
    method: Method,
    stats: &mut ReuseStats,
) -> Result<TimeSeries, Error> {
    if n0.len() != sys.chain.len() {
        return Err(Error::BadStructure(format!(
            "n0 length {} != chain size {}",
            n0.len(),
            sys.chain.len()
        )));
    }
    for (k, step) in steps.iter().enumerate() {
        if step.dt <= 0.0 || !step.dt.is_finite() {
            return Err(Error::BadStructure(format!(
                "invalid timestep dt at step {k}: {}",
                step.dt
            )));
        }
    }

    let energies = decay_energies_mev(sys);
    let mut times = Vec::with_capacity(steps.len() + 1);
    let mut atoms = Vec::with_capacity(steps.len() + 1);
    let mut activity = Vec::with_capacity(steps.len() + 1);
    let mut decay_heat = Vec::with_capacity(steps.len() + 1);

    times.push(0.0);
    atoms.push(n0.to_vec());
    activity.push(activity_vec(sys, n0));
    decay_heat.push(decay_heat_vec(sys, n0, &energies));

    let mut cache = SeriesCache::new();
    let mut n = n0.to_vec();
    let mut t = 0.0;
    for step in steps {
        n = cache.advance(sys, stats, &n, step, integrator, method)?;
        t += step.dt;
        times.push(t);
        activity.push(activity_vec(sys, &n));
        decay_heat.push(decay_heat_vec(sys, &n, &energies));
        atoms.push(n.clone());
    }

    Ok(TimeSeries {
        times,
        atoms,
        activity,
        decay_heat,
    })
}

/// Integrate with the historical CRAM-order selector.
///
/// Thin shim over [`integrate_with_method`] keeping the pre-`Method` call
/// shape; new code should pass an explicit [`Method`].
pub fn integrate(
    sys: &DepletionSystem,
    n0: &[f64],
    steps: &[Step],
    integrator: Integrator,
    order: Order,
) -> Result<TimeSeries, Error> {
    integrate_with_method(sys, n0, steps, integrator, Method::Cram(order))
}

/// Cross-step caches hoisted out of the per-step loop.
///
/// Reuse conditions (all checks exact, so reuse is bit-identical to fresh
/// per-step builds):
///
/// - `sys`: the [`DepletionSystem`] pattern/entries are reused while the
///   sparsity is unchanged; only `base_values` are recomputed per step via
///   [`DepletionSystem::refresh_rates`]. The pattern changes exactly when a
///   rate channel toggles between zero and nonzero (or the template chain
///   differs, which never happens inside one series).
/// - `sym`: the [`nucleide_linalg::SymbolicLu`] analysis depends only on the
///   sparsity pattern, so it is rebuilt only when the pattern changes
///   (constant-rate series build it once). CF4 scaled-matrix stages share
///   the pattern, so they reuse it too.
/// - `bateman`: the [`BatemanCache`] holds time-independent `C`/`C⁻¹` and is
///   reused while the assembled matrix values are bit-identical
///   (decay-only steps with an unchanged pattern). Any value or pattern
///   change re-probes; a probe that falls back to CRAM-48 is remembered for
///   those exact values so repeated fallback steps skip the rebuild.
struct SeriesCache {
    /// Working system: pattern/entries reused, `base_values` refreshed.
    sys: Option<DepletionSystem>,
    /// Symbolic analysis for the working system's pattern.
    sym: Option<nucleide_linalg::SymbolicLu>,
    /// Bateman decomposition for the current values, if the last probe
    /// succeeded.
    bateman: Option<BatemanCache>,
    /// `base_values` the Bateman slot was probed with (success or fallback).
    bateman_values: Option<Vec<nucleide_linalg::C64>>,
    /// The last probe for `bateman_values` fell back to CRAM-48.
    bateman_fallback: bool,
}

impl SeriesCache {
    fn new() -> Self {
        Self {
            sys: None,
            sym: None,
            bateman: None,
            bateman_values: None,
            bateman_fallback: false,
        }
    }

    /// Advance one step with the chosen integrator, reusing every
    /// time-independent object the step sequence allows.
    fn advance(
        &mut self,
        template: &DepletionSystem,
        stats: &mut ReuseStats,
        n: &[f64],
        step: &Step,
        integrator: Integrator,
        method: Method,
    ) -> Result<Vec<f64>, Error> {
        // Working system: built once, values refreshed per step; a sparsity
        // change fully rebuilds it and invalidates every derived cache.
        let pattern_changed = match self.sys.as_mut() {
            None => {
                self.sys = Some(DepletionSystem::build(template.chain.clone(), &step.rates)?);
                stats.system_builds += 1;
                true
            }
            Some(cur) => {
                if cur.refresh_rates(&step.rates)? {
                    false
                } else {
                    stats.system_builds += 1;
                    true
                }
            }
        };
        if pattern_changed {
            self.sym = None;
            self.bateman = None;
            self.bateman_values = None;
            self.bateman_fallback = false;
        }
        // Symbolic analysis: pattern-invariant, so at most one build per
        // distinct pattern in the series.
        if self.sym.is_none() {
            let sys = self.sys.as_ref().expect("working system built above");
            self.sym = Some(
                nucleide_linalg::SymbolicLu::try_new(&sys.pattern)
                    .map_err(|e| Error::BadStructure(e.to_string()))?,
            );
            stats.symbolic_builds += 1;
        }
        stats.steps += 1;

        match method {
            Method::Cram(order) => {
                let sys = self.sys.as_ref().expect("working system built above");
                let sym = self.sym.as_ref().expect("symbolic built above");
                advance_cram_cached(sys, sym, n, step, integrator, order)
            }
            Method::Bateman | Method::BatemanHp => {
                let hp = matches!(method, Method::BatemanHp);
                // Fast path: the cached decomposition matches these exact
                // values — only the `e^{−λdt}` diagonal is fresh per step.
                let values_match = self.bateman_values.as_ref().is_some_and(|v| {
                    values_equal(v, &self.sys.as_ref().expect("built").base_values)
                });
                if values_match {
                    if let Some(cache) = self.bateman.as_ref() {
                        return solve_bateman_staged(cache, n, step, integrator, hp);
                    }
                    // Known fallback for these exact values: CRAM-48 with the
                    // reused symbolic analysis (same dt-scaled staging as the
                    // probe path below).
                    debug_assert!(self.bateman_fallback);
                    let sys = self.sys.as_ref().expect("working system built above");
                    let sym = self.sym.as_ref().expect("symbolic built above");
                    return solve_cram48_fallback_staged(sys, sym, n, step, integrator);
                }
                // Slow path: probe the fast path for these exact values.
                stats.bateman_builds += 1;
                let sys = self.sys.as_ref().expect("working system built above");
                let sym = self.sym.as_ref().expect("symbolic built above");
                let snapshot = sys.base_values.clone();
                match BatemanCache::build(sys) {
                    Ok(cache) => {
                        let out = solve_bateman_staged(&cache, n, step, integrator, hp)?;
                        self.bateman = Some(cache);
                        self.bateman_values = Some(snapshot);
                        self.bateman_fallback = false;
                        Ok(out)
                    }
                    Err(_) => {
                        let out = solve_cram48_fallback_staged(sys, sym, n, step, integrator)?;
                        self.bateman = None;
                        self.bateman_values = Some(snapshot);
                        self.bateman_fallback = true;
                        Ok(out)
                    }
                }
            }
        }
    }
}

/// Bit-exact comparison of CRAM value vectors.
fn values_equal(a: &[nucleide_linalg::C64], b: &[nucleide_linalg::C64]) -> bool {
    a.len() == b.len()
        && a.iter()
            .zip(b)
            .all(|(x, y)| x.re.to_bits() == y.re.to_bits() && x.im.to_bits() == y.im.to_bits())
}

/// Bateman-arm staging for one step through a cached decomposition: the
/// integrator structure matches the pre-hoist dispatch exactly (CF4 stages
/// scale the timestep so the per-stage system stays in decay form).
fn solve_bateman_staged(
    cache: &BatemanCache,
    n: &[f64],
    step: &Step,
    integrator: Integrator,
    hp: bool,
) -> Result<Vec<f64>, Error> {
    let solve = |v: &[f64], dt: f64| {
        cache
            .solve(v, dt, hp)
            .map_err(|e| Error::BadStructure(e.to_string()))
    };
    match integrator {
        Integrator::Predictor => solve(n, step.dt),
        Integrator::Cecm => {
            let _pred = solve(n, step.dt)?;
            solve(n, step.dt)
        }
        Integrator::Cf4 => {
            let s1 = CF4_A11 + CF4_A12;
            let s2 = CF4_A12 + CF4_A11;
            let n1 = solve(n, s1 * step.dt)?;
            solve(&n1, s2 * step.dt)
        }
    }
}

/// CRAM-48 fallback staging for Bateman steps whose matrix carries
/// reaction/fission contributions (same dt-scaled staging as the Bateman
/// arms above, solved with the reused symbolic analysis).
fn solve_cram48_fallback_staged(
    sys: &DepletionSystem,
    sym: &nucleide_linalg::SymbolicLu,
    n: &[f64],
    step: &Step,
    integrator: Integrator,
) -> Result<Vec<f64>, Error> {
    let solve = |s: &DepletionSystem, v: &[f64], dt: f64| {
        crate::cram_with_symbolic(s, sym, Order::Order48, v, dt)
            .map_err(|e| Error::BadStructure(e.to_string()))
    };
    match integrator {
        Integrator::Predictor => solve(sys, n, step.dt),
        Integrator::Cecm => {
            let _pred = solve(sys, n, step.dt)?;
            solve(sys, n, step.dt)
        }
        Integrator::Cf4 => {
            let s1 = CF4_A11 + CF4_A12;
            let s2 = CF4_A12 + CF4_A11;
            let n1 = solve(sys, n, s1 * step.dt)?;
            solve(sys, &n1, s2 * step.dt)
        }
    }
}

/// Advance one step through the CRAM kernel with caller-managed caches
/// (preserves the historical scaled-matrix CF4 staging exactly; the scaled
/// stages share the working pattern so the symbolic analysis is reused).
fn advance_cram_cached(
    sys: &DepletionSystem,
    sym: &nucleide_linalg::SymbolicLu,
    n: &[f64],
    step: &Step,
    integrator: Integrator,
    order: Order,
) -> Result<Vec<f64>, Error> {
    let solve = |s: &DepletionSystem, v: &[f64], dt: f64| {
        crate::cram_with_symbolic(s, sym, order, v, dt)
            .map_err(|e| Error::BadStructure(e.to_string()))
    };
    match integrator {
        Integrator::Predictor => solve(sys, n, step.dt),
        Integrator::Cecm => {
            // Predictor with BOS rates, then corrector with the averaged
            // (BOS + EOS) / 2 matrix. Prescribed rates make EOS == BOS, so
            // the average reuses the same matrix (midpoint rate reuse); the
            // second CRAM keeps the two-solve CECM structure for future
            // flux-coupled EOS rates.
            let _pred = solve(sys, n, step.dt)?;
            // EOS rates equal BOS rates here; average is `sys` itself.
            solve(sys, n, step.dt)
        }
        Integrator::Cf4 => {
            // Two-exponential CF4: stage weights s1 = a11 + a12 and
            // s2 = a21 + a22 (both 1/2 with the coefficients above) scale
            // the stage matrices; with A1 == A2 == A_k each stage is a
            // half-step solve.
            let s1 = CF4_A11 + CF4_A12;
            let s2 = CF4_A12 + CF4_A11;
            let stage1 = scaled_system(sys, s1);
            let n1 = solve(&stage1, n, step.dt)?;
            let stage2 = scaled_system(sys, s2);
            solve(&stage2, &n1, step.dt)
        }
    }
}

/// Advance one step with the chosen integrator (fresh per-step builds).
///
/// Uncached oracle for the reuse regression tests: [`SeriesCache::advance`]
/// must reproduce this bit-for-bit on every step sequence. Kept in sync with
/// the staged solvers above by construction (same stage structure, same
/// kernels, only the caches differ).
#[cfg(test)]
fn advance(
    sys: &DepletionSystem,
    n: &[f64],
    step: &Step,
    integrator: Integrator,
    method: Method,
) -> Result<Vec<f64>, Error> {
    let mat = || DepletionSystem::build(sys.chain.clone(), &step.rates);
    let solve = |s: &DepletionSystem, v: &[f64], dt: f64| {
        crate::solve_with_method(s, method, v, dt).map_err(|e| Error::BadStructure(e.to_string()))
    };
    match method {
        Method::Cram(order) => advance_cram(n, step, integrator, order, &mat),
        Method::Bateman | Method::BatemanHp => {
            // Same integrator structure, but each exponential runs through
            // the method dispatcher (Bateman steps with live rates fall back
            // to CRAM-48 inside `solve_with_method`). CF4 stages scale the
            // timestep rather than the matrix so the per-stage system stays
            // in decay reconstruction form.
            let sys_k = mat()?;
            match integrator {
                Integrator::Predictor => solve(&sys_k, n, step.dt),
                Integrator::Cecm => {
                    let _pred = solve(&sys_k, n, step.dt)?;
                    solve(&sys_k, n, step.dt)
                }
                Integrator::Cf4 => {
                    let s1 = CF4_A11 + CF4_A12;
                    let s2 = CF4_A12 + CF4_A11;
                    let n1 = solve(&sys_k, n, s1 * step.dt)?;
                    solve(&sys_k, &n1, s2 * step.dt)
                }
            }
        }
    }
}

/// Advance one step through the CRAM kernel (preserves the historical
/// scaled-matrix CF4 staging exactly).
#[cfg(test)]
fn advance_cram(
    n: &[f64],
    step: &Step,
    integrator: Integrator,
    order: Order,
    mat: &dyn Fn() -> Result<DepletionSystem, Error>,
) -> Result<Vec<f64>, Error> {
    match integrator {
        Integrator::Predictor => {
            let sys_k = mat()?;
            crate::cram(&sys_k, order, n, step.dt).map_err(|e| Error::BadStructure(e.to_string()))
        }
        Integrator::Cecm => {
            // Predictor with BOS rates, then corrector with the averaged
            // (BOS + EOS) / 2 matrix. Prescribed rates make EOS == BOS, so
            // the average reuses the same matrix (midpoint rate reuse); the
            // second CRAM keeps the two-solve CECM structure for future
            // flux-coupled EOS rates.
            let sys_k = mat()?;
            let _pred = crate::cram(&sys_k, order, n, step.dt)
                .map_err(|e| Error::BadStructure(e.to_string()))?;
            // EOS rates equal BOS rates here; average is `sys_k` itself.
            crate::cram(&sys_k, order, n, step.dt).map_err(|e| Error::BadStructure(e.to_string()))
        }
        Integrator::Cf4 => {
            // Two-exponential CF4: stage weights s1 = a11 + a12 and
            // s2 = a21 + a22 (both 1/2 with the coefficients above) scale
            // the stage matrices; with A1 == A2 == A_k each stage is a
            // half-step solve.
            let sys_k = mat()?;
            let s1 = CF4_A11 + CF4_A12;
            let s2 = CF4_A12 + CF4_A11;
            let stage1 = scaled_system(&sys_k, s1);
            let n1 = crate::cram(&stage1, order, n, step.dt)
                .map_err(|e| Error::BadStructure(e.to_string()))?;
            let stage2 = scaled_system(&sys_k, s2);
            crate::cram(&stage2, order, &n1, step.dt)
                .map_err(|e| Error::BadStructure(e.to_string()))
        }
    }
}

/// Clone a system with all matrix entries scaled by `scale`
/// (used for CF4 half-step stages; pattern and diagonal layout are kept).
fn scaled_system(sys: &DepletionSystem, scale: f64) -> DepletionSystem {
    let mut out = sys.clone();
    for v in &mut out.base_values {
        *v *= scale;
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::chain::{Chain, ChainNuclide, DecayMode};

    const L1: f64 = 1.0e-6;
    const L2: f64 = 1.0e-5;

    fn abc_chain() -> Chain {
        let a = ChainNuclide {
            name: "A".into(),
            half_life: Some(std::f64::consts::LN_2 / L1),
            decay_modes: vec![DecayMode {
                kind: "beta".into(),
                target: "B".into(),
                branching_ratio: 1.0,
            }],
            ..Default::default()
        };
        let b = ChainNuclide {
            name: "B".into(),
            half_life: Some(std::f64::consts::LN_2 / L2),
            decay_modes: vec![DecayMode {
                kind: "beta".into(),
                target: "C".into(),
                branching_ratio: 1.0,
            }],
            ..Default::default()
        };
        let c = ChainNuclide {
            name: "C".into(),
            ..Default::default()
        };
        Chain::from_nuclides(vec![a, b, c]).unwrap()
    }

    /// Analytic Bateman solution for A -> B -> C from pure A.
    fn bateman(n0: f64, t: f64) -> [f64; 3] {
        let na = n0 * (-L1 * t).exp();
        let nb = n0 * L1 / (L2 - L1) * ((-L1 * t).exp() - (-L2 * t).exp());
        let nc = n0 - na - nb;
        [na, nb, nc]
    }

    fn constant_steps(dt: f64, count: usize) -> Vec<Step> {
        (0..count)
            .map(|_| Step::new(dt, ReactionRates::new()))
            .collect()
    }

    fn max_rel_err(got: &[f64], want: &[f64]) -> f64 {
        got.iter()
            .zip(want)
            .map(|(g, w)| (g - w).abs() / w.max(1e-30))
            .fold(0.0_f64, f64::max)
    }

    #[test]
    fn predictor_matches_bateman() {
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let n0 = vec![1.0e15, 0.0, 0.0];
        let steps = constant_steps(2.0e4, 5);
        let ts = integrate(&sys, &n0, &steps, Integrator::Predictor, Order::Order48).unwrap();

        assert_eq!(ts.len(), 6);
        assert_eq!(ts.times[0], 0.0);
        assert_eq!(*ts.times.last().unwrap(), 1.0e5);
        // Initial row echoes n0.
        assert_eq!(ts.atoms[0], n0);
        // Every node matches the analytic solution at its cumulative time.
        for (k, t) in ts.times.iter().enumerate() {
            let want = bateman(n0[0], *t);
            let err = max_rel_err(&ts.atoms[k], &want);
            assert!(err < 1e-6, "node {k} t={t}: err {err}");
        }
    }

    #[test]
    fn cecm_matches_bateman() {
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let n0 = vec![1.0e15, 0.0, 0.0];
        let steps = constant_steps(2.0e4, 5);
        let ts = integrate(&sys, &n0, &steps, Integrator::Cecm, Order::Order48).unwrap();

        for (k, t) in ts.times.iter().enumerate() {
            let want = bateman(n0[0], *t);
            let err = max_rel_err(&ts.atoms[k], &want);
            assert!(err < 1e-6, "node {k} t={t}: err {err}");
        }
    }

    #[test]
    fn cf4_matches_or_beats_predictor() {
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let n0 = vec![1.0e15, 0.0, 0.0];
        // Coarse steps with the cheaper order so the CRAM-argument
        // difference between one full step and two half steps is visible.
        let steps = constant_steps(2.0e5, 4);
        let pred = integrate(&sys, &n0, &steps, Integrator::Predictor, Order::Order16).unwrap();
        let cf4 = integrate(&sys, &n0, &steps, Integrator::Cf4, Order::Order16).unwrap();

        let total_t = 8.0e5;
        let want = bateman(n0[0], total_t);
        let pred_err = max_rel_err(pred.atoms.last().unwrap(), &want);
        let cf4_err = max_rel_err(cf4.atoms.last().unwrap(), &want);
        assert!(pred_err < 1e-4, "predictor err {pred_err}");
        assert!(
            cf4_err <= pred_err,
            "cf4 err {cf4_err} should be <= predictor err {pred_err}"
        );
    }

    #[test]
    fn atoms_conserved_along_series() {
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let n0 = vec![1.0e15, 0.0, 0.0];
        let steps = constant_steps(2.0e4, 5);
        for integrator in [Integrator::Predictor, Integrator::Cecm, Integrator::Cf4] {
            let ts = integrate(&sys, &n0, &steps, integrator, Order::Order48).unwrap();
            for (k, row) in ts.atoms.iter().enumerate() {
                let total: f64 = row.iter().sum();
                let err = (total - n0[0]).abs() / n0[0];
                assert!(err < 1e-8, "{integrator:?} node {k}: err {err}");
            }
        }
    }

    #[test]
    fn invalid_dt_rejected() {
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let n0 = vec![1.0e15, 0.0, 0.0];
        for bad in [0.0, -1.0, f64::NAN, f64::INFINITY] {
            let steps = vec![Step::new(bad, ReactionRates::new())];
            assert!(
                integrate(&sys, &n0, &steps, Integrator::Predictor, Order::Order48).is_err(),
                "dt={bad} should fail"
            );
        }
        // Dimension mismatch also fails.
        let steps = constant_steps(1.0, 1);
        assert!(integrate(&sys, &[1.0], &steps, Integrator::Predictor, Order::Order48).is_err());
    }

    #[test]
    fn bateman_series_matches_predictor_band() {
        use crate::bateman::Method;
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let n0 = vec![1.0e15, 0.0, 0.0];
        let steps = constant_steps(2.0e4, 5);
        let cref = integrate_with_method(
            &sys,
            &n0,
            &steps,
            Integrator::Predictor,
            Method::default_cram(),
        )
        .unwrap();
        for method in [Method::Bateman, Method::BatemanHp] {
            let ts =
                integrate_with_method(&sys, &n0, &steps, Integrator::Predictor, method).unwrap();
            assert_eq!(ts.times, cref.times);
            for (k, (row, ref_row)) in ts.atoms.iter().zip(&cref.atoms).enumerate() {
                for (g, c) in row.iter().zip(ref_row) {
                    assert!((g - c).abs() / c.max(1e-30) < 1e-6, "node {k}: {g} vs {c}");
                }
                let want = bateman(n0[0], ts.times[k]);
                assert!(max_rel_err(row, &want) < 1e-6, "node {k}");
                let total: f64 = row.iter().sum();
                assert!((total - n0[0]).abs() / n0[0] < 1e-8, "node {k}");
            }
        }
    }

    #[test]
    fn bateman_series_with_rates_falls_back_to_cram() {
        use crate::bateman::Method;
        // Capture channel on A with a live rate: Bateman steps must
        // reproduce the CRAM series exactly (fallback inside the kernel).
        let a = ChainNuclide {
            name: "A".into(),
            half_life: Some(std::f64::consts::LN_2 / L1),
            decay_modes: vec![DecayMode {
                kind: "beta".into(),
                target: "B".into(),
                branching_ratio: 1.0,
            }],
            reactions: vec![crate::chain::Reaction {
                kind: "(n,gamma)".into(),
                target: Some("B".into()),
                q: 0.0,
                branching_ratio: 1.0,
            }],
            ..Default::default()
        };
        let b = ChainNuclide {
            name: "B".into(),
            half_life: Some(std::f64::consts::LN_2 / L2),
            decay_modes: vec![DecayMode {
                kind: "beta".into(),
                target: "C".into(),
                branching_ratio: 1.0,
            }],
            ..Default::default()
        };
        let c = ChainNuclide {
            name: "C".into(),
            ..Default::default()
        };
        let chain = Chain::from_nuclides(vec![a, b, c]).unwrap();
        let sys = DepletionSystem::build(chain, &ReactionRates::new()).unwrap();
        let mut rates = ReactionRates::new();
        rates
            .entry(0usize)
            .or_default()
            .insert("(n,gamma)".to_string(), 1e-7);
        let steps: Vec<Step> = (0..3).map(|_| Step::new(2.0e4, rates.clone())).collect();
        let n0 = vec![1.0e15, 0.0, 0.0];
        let cref = integrate_with_method(
            &sys,
            &n0,
            &steps,
            Integrator::Predictor,
            Method::default_cram(),
        )
        .unwrap();
        let got =
            integrate_with_method(&sys, &n0, &steps, Integrator::Predictor, Method::BatemanHp)
                .unwrap();
        assert_eq!(got.atoms, cref.atoms);
    }

    #[test]
    fn reuse_decay_series_builds_once_and_matches_oracle() {
        use crate::bateman::Method;
        // Finding 1: one BatemanCache for a decay-only series with an
        // unchanged pattern; only the `e^{-λdt}` diagonal is fresh per step.
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let n0 = vec![1.0e15, 0.0, 0.0];
        let steps = constant_steps(2.0e4, 6);
        for method in [Method::Bateman, Method::BatemanHp] {
            let mut stats = ReuseStats::default();
            let ts = integrate_with_method_counted(
                &sys,
                &n0,
                &steps,
                Integrator::Predictor,
                method,
                &mut stats,
            )
            .unwrap();
            assert_eq!(
                stats,
                ReuseStats {
                    steps: 6,
                    system_builds: 1,
                    symbolic_builds: 1,
                    bateman_builds: 1,
                },
                "{method:?}"
            );
            // Bit-identical to fresh per-step builds on every node.
            let mut n = n0.clone();
            for (k, step) in steps.iter().enumerate() {
                n = advance(&sys, &n, step, Integrator::Predictor, method).unwrap();
                assert_eq!(ts.atoms[k + 1], n, "{method:?} node {}", k + 1);
            }
            // Identical Bateman-vs-analytic gates as the uncached path.
            for (k, t) in ts.times.iter().enumerate() {
                let want = bateman(n0[0], *t);
                assert!(
                    max_rel_err(&ts.atoms[k], &want) < 1e-6,
                    "{method:?} node {k}"
                );
                let total: f64 = ts.atoms[k].iter().sum();
                assert!((total - n0[0]).abs() / n0[0] < 1e-8, "{method:?} node {k}");
            }
        }
    }

    #[test]
    fn reuse_cram_constant_series_builds_once_and_holds_bands() {
        use crate::bateman::Method;
        // Finding 2: one SymbolicLu for a step-invariant sparsity pattern;
        // Predictor/CeCM/CF4 bands are unchanged (all within 1e-6 of the
        // analytic chain) and bit-identical to fresh per-step builds.
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let n0 = vec![1.0e15, 0.0, 0.0];
        let steps = constant_steps(2.0e4, 5);
        for integrator in [Integrator::Predictor, Integrator::Cecm, Integrator::Cf4] {
            let mut stats = ReuseStats::default();
            let ts = integrate_with_method_counted(
                &sys,
                &n0,
                &steps,
                integrator,
                Method::default_cram(),
                &mut stats,
            )
            .unwrap();
            assert_eq!(
                stats,
                ReuseStats {
                    steps: 5,
                    system_builds: 1,
                    symbolic_builds: 1,
                    bateman_builds: 0,
                },
                "{integrator:?}"
            );
            let mut n = n0.clone();
            for (k, step) in steps.iter().enumerate() {
                n = advance(&sys, &n, step, integrator, Method::default_cram()).unwrap();
                assert_eq!(ts.atoms[k + 1], n, "{integrator:?} node {}", k + 1);
            }
            for (k, t) in ts.times.iter().enumerate() {
                let want = bateman(n0[0], *t);
                assert!(
                    max_rel_err(&ts.atoms[k], &want) < 1e-6,
                    "{integrator:?} node {k}"
                );
            }
        }
    }

    #[test]
    fn reuse_invalidates_on_pattern_and_value_change() {
        use crate::bateman::Method;
        // Finding 3: pattern/entries are reused while only base_values change;
        // a zero/nonzero channel toggle rebuilds, a value-only change only
        // re-probes the Bateman slot. Results stay bit-identical to fresh
        // per-step builds throughout.
        let a = ChainNuclide {
            name: "A".into(),
            half_life: Some(std::f64::consts::LN_2 / L1),
            decay_modes: vec![DecayMode {
                kind: "beta".into(),
                target: "B".into(),
                branching_ratio: 1.0,
            }],
            reactions: vec![crate::chain::Reaction {
                kind: "(n,gamma)".into(),
                // Capture to C: no decay edge (C, A) exists, so toggling the
                // rate changes the sparsity pattern (decay A -> B keeps the
                // (B, A) entry either way).
                target: Some("C".into()),
                q: 0.0,
                branching_ratio: 1.0,
            }],
            ..Default::default()
        };
        let b = ChainNuclide {
            name: "B".into(),
            half_life: Some(std::f64::consts::LN_2 / L2),
            decay_modes: vec![DecayMode {
                kind: "beta".into(),
                target: "C".into(),
                branching_ratio: 1.0,
            }],
            ..Default::default()
        };
        let c = ChainNuclide {
            name: "C".into(),
            ..Default::default()
        };
        let chain = Chain::from_nuclides(vec![a, b, c]).unwrap();
        let sys = DepletionSystem::build(chain, &ReactionRates::new()).unwrap();
        let mut r1 = ReactionRates::new();
        r1.entry(0usize)
            .or_default()
            .insert("(n,gamma)".to_string(), 1e-7);
        let mut r2 = ReactionRates::new();
        r2.entry(0usize)
            .or_default()
            .insert("(n,gamma)".to_string(), 2e-7);
        let steps = vec![
            Step::new(2.0e4, r1.clone()),
            Step::new(2.0e4, r1.clone()),
            Step::new(2.0e4, r2.clone()),
            Step::new(2.0e4, ReactionRates::new()),
        ];
        let n0 = vec![1.0e15, 0.0, 0.0];
        let mut stats = ReuseStats::default();
        let ts = integrate_with_method_counted(
            &sys,
            &n0,
            &steps,
            Integrator::Predictor,
            Method::BatemanHp,
            &mut stats,
        )
        .unwrap();
        // One initial build + one rebuild on the decay-only pattern change;
        // one symbolic analysis per distinct pattern; one Bateman probe per
        // distinct value set (r1 fallback, r1 hit, r2 fallback, decay probe).
        assert_eq!(
            stats,
            ReuseStats {
                steps: 4,
                system_builds: 2,
                symbolic_builds: 2,
                bateman_builds: 3,
            },
            "{stats:?}"
        );
        let mut n = n0.clone();
        for (k, step) in steps.iter().enumerate() {
            n = advance(&sys, &n, step, Integrator::Predictor, Method::BatemanHp).unwrap();
            assert_eq!(ts.atoms[k + 1], n, "node {}", k + 1);
        }
    }

    #[test]
    fn refresh_rates_matches_fresh_build() {
        // `refresh_rates` reuses the pattern for value-only changes and
        // rebuilds on sparsity changes, bit-identical to fresh builds.
        // A is stable with only a capture channel, so zeroing the rate
        // removes entries (with a decay A -> B edge the pattern would be
        // unchanged either way).
        let a = ChainNuclide {
            name: "A".into(),
            reactions: vec![crate::chain::Reaction {
                kind: "(n,gamma)".into(),
                target: Some("B".into()),
                q: 0.0,
                branching_ratio: 1.0,
            }],
            ..Default::default()
        };
        let b = ChainNuclide {
            name: "B".into(),
            ..Default::default()
        };
        let chain = Chain::from_nuclides(vec![a, b]).unwrap();
        let mut r1 = ReactionRates::new();
        r1.entry(0usize)
            .or_default()
            .insert("(n,gamma)".to_string(), 1e-7);
        let mut r2 = ReactionRates::new();
        r2.entry(0usize)
            .or_default()
            .insert("(n,gamma)".to_string(), 3e-7);
        let mut sys = DepletionSystem::build(chain.clone(), &r1).unwrap();
        assert!(sys.refresh_rates(&r2).unwrap());
        let fresh = DepletionSystem::build(chain.clone(), &r2).unwrap();
        assert_eq!(sys.entries, fresh.entries);
        assert_eq!(sys.base_values, fresh.base_values);
        // Zeroing the channel changes sparsity: full rebuild, still identical.
        assert!(!sys.refresh_rates(&ReactionRates::new()).unwrap());
        let fresh_decay = DepletionSystem::build(chain, &ReactionRates::new()).unwrap();
        assert_eq!(sys.entries, fresh_decay.entries);
        assert_eq!(sys.base_values, fresh_decay.base_values);
    }

    #[test]
    fn activity_and_decay_heat_spot_check() {
        let nuc = ChainNuclide {
            name: "Solo".into(),
            half_life: Some(std::f64::consts::LN_2 / L1),
            decay_energy: 2.0e6, // 2 MeV in eV
            ..Default::default()
        };
        let sys = DepletionSystem::build(
            Chain::from_nuclides(vec![nuc]).unwrap(),
            &ReactionRates::new(),
        )
        .unwrap();
        let n = vec![1.0e12];
        let act = activity_vec(&sys, &n);
        assert_eq!(act.len(), 1);
        assert!((act[0] - L1 * 1.0e12).abs() / act[0] < 1e-12);

        let heat = decay_heat_vec(&sys, &n, &decay_energies_mev(&sys));
        let want = L1 * 1.0e12 * 2.0 * MEV_TO_JOULE;
        assert!((heat[0] - want).abs() / want < 1e-12);

        // Chain energy (eV -> MeV) wins over the fallback table.
        assert_eq!(decay_energies_mev(&sys), vec![2.0]);
    }

    #[test]
    fn decay_energy_table_and_zero_behavior() {
        // Unknown synthetic nuclide without chain energy -> 0.0.
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        assert_eq!(decay_energies_mev(&sys), vec![0.0, 0.0, 0.0]);
        let heat = decay_heat_vec(&sys, &[1.0e10, 1.0e10, 1.0e10], &decay_energies_mev(&sys));
        assert_eq!(heat, vec![0.0, 0.0, 0.0]);

        // Real nuclide resolves through the ENDF/B-VII.1 table (Cs137 prompt
        // mean, excluding the Ba137_m1 daughter gamma).
        let chain = Chain::from_nuclides(vec![ChainNuclide {
            name: "Cs137".into(),
            half_life: Some(9.49e8),
            ..Default::default()
        }])
        .unwrap();
        let sys = DepletionSystem::build(chain, &ReactionRates::new()).unwrap();
        let e = decay_energies_mev(&sys)[0];
        assert!((e - 0.1794).abs() / 0.1794 < 0.05, "{e}");
    }

    #[test]
    fn series_carries_activity_and_heat_rows() {
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let n0 = vec![1.0e15, 0.0, 0.0];
        let steps = constant_steps(2.0e4, 3);
        let ts = integrate(&sys, &n0, &steps, Integrator::Predictor, Order::Order48).unwrap();
        assert_eq!(ts.activity.len(), ts.len());
        assert_eq!(ts.decay_heat.len(), ts.len());
        // t = 0 activity is exact: only A is present.
        assert!((ts.activity[0][0] - L1 * n0[0]).abs() / ts.activity[0][0] < 1e-12);
        assert_eq!(ts.activity[0][1], 0.0);
        // Mid-series B activity matches Bateman through the helper.
        let want_b = bateman(n0[0], ts.times[2])[1] * L2;
        assert!((ts.activity[2][1] - want_b).abs() / want_b < 1e-6);
    }

    #[test]
    fn time_series_accessors() {
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let n0 = vec![1.0e15, 0.0, 0.0];
        let steps = constant_steps(2.0e4, 2);
        let ts = integrate(&sys, &n0, &steps, Integrator::Predictor, Order::Order48).unwrap();
        assert_eq!(ts.len(), 3);
        assert!(!ts.is_empty());
        assert_eq!(ts.nuclides(), 3);
        // An empty series is only constructible field-by-field.
        let empty = TimeSeries {
            times: vec![],
            atoms: vec![],
            activity: vec![],
            decay_heat: vec![],
        };
        assert!(empty.is_empty());
        assert_eq!(empty.nuclides(), 0);
    }

    #[test]
    fn decay_energies_by_name_match_chain_order() {
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let by_name = decay_energies_by_name(&sys.chain);
        assert_eq!(by_name.len(), 3);
        // Name-keyed map and chain-order vector agree entry by entry.
        for (nuc, e) in sys.chain.nuclides.iter().zip(decay_energies_mev(&sys)) {
            assert_eq!(by_name[&nuc.name], e);
        }
        // Synthetic nuclides without chain energy resolve to 0.0.
        assert_eq!(by_name["A"], 0.0);
        // Real nuclide resolves through the ENDF table in the map view too.
        let cs = Chain::from_nuclides(vec![ChainNuclide {
            name: "Cs137".into(),
            half_life: Some(9.49e8),
            ..Default::default()
        }])
        .unwrap();
        let e = decay_energies_by_name(&cs)["Cs137"];
        assert!((e - 0.1794).abs() / 0.1794 < 0.05, "{e}");
    }

    #[test]
    #[should_panic(expected = "nvec length 1 != chain size 3")]
    fn activity_vec_rejects_length_mismatch() {
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        activity_vec(&sys, &[1.0]);
    }

    #[test]
    #[should_panic(expected = "nvec length 1 != chain size 3")]
    fn decay_heat_vec_rejects_nvec_length_mismatch() {
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        decay_heat_vec(&sys, &[1.0], &decay_energies_mev(&sys));
    }

    #[test]
    #[should_panic(expected = "energies length 1 != chain size 3")]
    fn decay_heat_vec_rejects_energy_length_mismatch() {
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        decay_heat_vec(&sys, &[1.0e10, 0.0, 0.0], &[1.0]);
    }

    #[test]
    fn bateman_decay_series_all_integrators_match_oracle() {
        use crate::bateman::Method;
        // Cecm/Cf4 staging through the cached Bateman path: one build per
        // series, and bit-identical to the fresh per-step oracle on every
        // node (the oracle dispatches through the same analytic kernel).
        let sys = DepletionSystem::build(abc_chain(), &ReactionRates::new()).unwrap();
        let n0 = vec![1.0e15, 0.0, 0.0];
        let steps = constant_steps(2.0e4, 4);
        for method in [Method::Bateman, Method::BatemanHp] {
            for integrator in [Integrator::Cecm, Integrator::Cf4] {
                let mut stats = ReuseStats::default();
                let ts = integrate_with_method_counted(
                    &sys, &n0, &steps, integrator, method, &mut stats,
                )
                .unwrap();
                assert_eq!(
                    stats,
                    ReuseStats {
                        steps: 4,
                        system_builds: 1,
                        symbolic_builds: 1,
                        bateman_builds: 1,
                    },
                    "{method:?} {integrator:?}"
                );
                let mut n = n0.clone();
                for (k, step) in steps.iter().enumerate() {
                    n = advance(&sys, &n, step, integrator, method).unwrap();
                    assert_eq!(
                        ts.atoms[k + 1],
                        n,
                        "{method:?} {integrator:?} node {}",
                        k + 1
                    );
                }
                // Same analytic band as the Predictor arm.
                for (k, t) in ts.times.iter().enumerate() {
                    let want = bateman(n0[0], *t);
                    assert!(
                        max_rel_err(&ts.atoms[k], &want) < 1e-6,
                        "{method:?} {integrator:?} node {k}"
                    );
                }
            }
        }
    }

    #[test]
    fn bateman_fallback_series_all_integrators_match_oracle() {
        use crate::bateman::Method;
        // Live capture rate on A: every step falls back to CRAM-48 inside
        // the kernel (probe on step 1, cached fallback arm on steps 2+).
        // Cecm/Cf4 staging is bit-identical to the fresh per-step oracle and
        // stays within roundoff of the CRAM-method series.
        let a = ChainNuclide {
            name: "A".into(),
            half_life: Some(std::f64::consts::LN_2 / L1),
            decay_modes: vec![DecayMode {
                kind: "beta".into(),
                target: "B".into(),
                branching_ratio: 1.0,
            }],
            reactions: vec![crate::chain::Reaction {
                kind: "(n,gamma)".into(),
                target: Some("B".into()),
                q: 0.0,
                branching_ratio: 1.0,
            }],
            ..Default::default()
        };
        let b = ChainNuclide {
            name: "B".into(),
            half_life: Some(std::f64::consts::LN_2 / L2),
            decay_modes: vec![DecayMode {
                kind: "beta".into(),
                target: "C".into(),
                branching_ratio: 1.0,
            }],
            ..Default::default()
        };
        let c = ChainNuclide {
            name: "C".into(),
            ..Default::default()
        };
        let chain = Chain::from_nuclides(vec![a, b, c]).unwrap();
        let sys = DepletionSystem::build(chain, &ReactionRates::new()).unwrap();
        let mut rates = ReactionRates::new();
        rates
            .entry(0usize)
            .or_default()
            .insert("(n,gamma)".to_string(), 1e-7);
        let steps: Vec<Step> = (0..3).map(|_| Step::new(2.0e4, rates.clone())).collect();
        let n0 = vec![1.0e15, 0.0, 0.0];
        for integrator in [Integrator::Cecm, Integrator::Cf4] {
            let cref = integrate_with_method(&sys, &n0, &steps, integrator, Method::default_cram())
                .unwrap();
            for method in [Method::Bateman, Method::BatemanHp] {
                let got = integrate_with_method(&sys, &n0, &steps, integrator, method).unwrap();
                let mut n = n0.clone();
                for (k, step) in steps.iter().enumerate() {
                    n = advance(&sys, &n, step, integrator, method).unwrap();
                    assert_eq!(
                        got.atoms[k + 1],
                        n,
                        "{method:?} {integrator:?} node {}",
                        k + 1
                    );
                }
                for (k, row) in got.atoms.iter().enumerate() {
                    let err = max_rel_err(row, &cref.atoms[k]);
                    assert!(err < 1e-9, "{method:?} {integrator:?} node {k}: {err}");
                }
            }
        }
    }
}
